import path from "path";
import fs from "fs";

import { match } from "../consts";
export const generateGamesTS = () => {
  // Define the directory where your game data JSON files are stored
  // This MUST match the DATA_DIR in 'scripts/buildGameData.ts'
  const GAMES_DIR = path.join(process.cwd(), "results");

  console.log(GAMES_DIR);

  // Create a simple in-memory cache to avoid re-reading files during build
  /**
   * Reads all .json files from the game data directory,
   * parses them, and returns them as an array of 'match' objects.
   * This function is intended to be used ONLY in server-side code
   * (like getStaticProps, getStaticPaths, or API routes).
   */
  function loadAllGames(): match[] {
    // If cache exists, return it

    if (!fs.existsSync(GAMES_DIR)) {
      console.warn(`Directory not found: ${GAMES_DIR}. Returning empty array.`);

      return [];
    }

    const filenames = fs.readdirSync(GAMES_DIR);

    const games = filenames
      .filter((filename: string) => filename.endsWith(".json"))
      .map((filename: string) => {
        const filePath = path.join(GAMES_DIR, filename);
        const fileContents = fs.readFileSync(filePath, "utf-8");
        const gameData: match = JSON.parse(fileContents);

        return gameData;
      });

    // Sort games by week, descending (newest first)
    games.sort((a: { week: number }, b: { week: number }) => b.week - a.week);

    console.log(`Loaded ${games.length} games.`);

    return games;
  }

  // REMOVED the line that executed the function:
  //   const GAMES: match[] = loadAllGames();
  //   console.log(GAMES);
  return loadAllGames();
};

function writeGeneratedTSFile(games: match[]) {
  if (!games || games.length === 0) {
    console.log("No games found to write. Skipping file generation.");

    return;
  }

  // This is the content that will be written to the file
  const fileContent = `
// THIS FILE IS AUTO-GENERATED BY 'utils/gameRunner/runGames.ts'
// DO NOT EDIT THIS FILE MANUALLY

import { match } from '../../consts';

export const GAMES: match[] = ${JSON.stringify(games, null, 2)};
`;

  // Define the output path robustly
  const OUTPUT_FILE = path.join(process.cwd(), "utils", "games.generated.ts");
  const outputDir = path.dirname(OUTPUT_FILE);

  try {
    // Ensure the 'utils' directory exists
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }

    // Write the file synchronously
    fs.writeFileSync(OUTPUT_FILE, fileContent, "utf8");
    console.log(`Successfully generated: ${OUTPUT_FILE}`);
  } catch (err) {
    console.error("Error writing games.generated.ts file:", err);
  }
}

// --- Main Execution ---
const allGamesData = generateGamesTS();

writeGeneratedTSFile(allGamesData);
