import path from "path";
import fs from "fs";

import { match } from "@/utils/types";
import {
  generateDiscordAnnouncement,
  generatePopularityPost,
  generateWeeklyReport,
  generateCelebrityPost,
  generateRecapSummary,
} from "./gameFiles/gameReportGenerator";

export const generateGamesTS = () => {
  // Define the directory where your game data JSON files are stored
  // This MUST match the DATA_DIR in 'scripts/buildGameData.ts'
  const GAMES_DIR = path.join(process.cwd(), "utils", "gameRunner", "results");

  console.log(GAMES_DIR);

  // Create a simple in-memory cache to avoid re-reading files during build
  /**
   * Reads all .json files from the game data directory,
   * parses them, and returns them as an array of 'match' objects.
   * This function is intended to be used ONLY in server-side code
   * (like getStaticProps, getStaticPaths, or API routes).
   */
  function loadAllGames(): match[] {
    // If cache exists, return it

    if (!fs.existsSync(GAMES_DIR)) {
      console.warn(`Directory not found: ${GAMES_DIR}. Returning empty array.`);

      return [];
    }

    const filenames = fs.readdirSync(GAMES_DIR);

    const games = filenames
      .filter(
        (filename: string) =>
          filename.endsWith(".json") && !filename.includes("weeklyRecap"),
      )
      .map((filename: string) => {
        const filePath = path.join(GAMES_DIR, filename);
        const fileContents = fs.readFileSync(filePath, "utf-8");
        const gameData: match = JSON.parse(fileContents);

        return {
          ...gameData,
          plays: gameData.plays || [],
        };
      });

    // Sort games by week, descending (newest first)
    games.sort((a: { week: number }, b: { week: number }) => b.week - a.week);

    console.log(`Loaded ${games.length} games.`);

    return games;
  }

  // REMOVED the line that executed the function:
  //   const GAMES: match[] = loadAllGames();
  //   console.log(GAMES);
  return loadAllGames();
};

// Create a simple in-memory cache to avoid re-reading files during build
const loadAllRecaps = () => {
  const GAMES_DIR = path.join(process.cwd(), "results");

  console.log(GAMES_DIR);
  if (!fs.existsSync(GAMES_DIR)) {
    console.log(`Directory not found: ${GAMES_DIR}. Returning empty array.`);
    return [];
  }
  const filenames = fs.readdirSync(GAMES_DIR);

  const recaps = filenames
    .filter(
      (filename: string) =>
        filename.endsWith(".json") &&
        (filename.includes("weeklyRecap") ||
          filename.includes("celebrityPost") || filename.includes("runeReading")),
    )
    .map((filename: string) => {
      const filePath = path.join(GAMES_DIR, filename);
      const fileContents = fs.readFileSync(filePath, "utf-8");
      const gameData: match = JSON.parse(fileContents);

      return {
        ...gameData,
        plays: gameData.plays || [],
      };
    });
  return recaps;
};

function writeGeneratedTSFile(games: match[]) {
  if (!games || games.length === 0) {
    console.log("No games found to write. Skipping file generation.");

    return;
  }

  games.forEach((game) => {
    if ("name" in game.awayTeam) {
      game.awayTeam.players = [];
      game.awayTeam.activePlayers = undefined;
      game.awayTeam.inactivePlayers = undefined;
    }
    if ("name" in game.homeTeam) {
      game.homeTeam.players = [];
      game.homeTeam.activePlayers = undefined;
      game.homeTeam.inactivePlayers = undefined;
    }
  });

  // This is the content that will be written to the file
  const fileContent = `
// THIS FILE IS AUTO-GENERATED BY 'utils/gameRunner/runGames.ts'
// DO NOT EDIT THIS FILE MANUALLY

import { match } from './types';

export const GAMES: match[] = ${JSON.stringify(games, null, 2)};
`;

  // Define the output path robustly
  const OUTPUT_FILE = path.join(process.cwd(), "utils", "games.generated.ts");
  const outputDir = path.dirname(OUTPUT_FILE);

  try {
    // Ensure the 'utils' directory exists
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }

    // Write the file synchronously
    fs.writeFileSync(OUTPUT_FILE, fileContent, "utf8");
    console.log(`Successfully generated: ${OUTPUT_FILE}`);
  } catch (err) {
    console.error("Error writing games.generated.ts file:", err);
  }
}

async function makeWeeklyRecap(allGamesData: match[]) {
  const week = Math.max(...allGamesData.map((game) => game.week));
  const pastRecaps = loadAllRecaps();

  // Generate or load the summary of past context
  const SUMMARY_FILE = path.join(process.cwd(), "results", "recapSummary.json");
  let pastRecapsSummary = "";

  if (fs.existsSync(SUMMARY_FILE)) {
    console.log("Loading summary from existing file...");
    pastRecapsSummary = fs.readFileSync(SUMMARY_FILE, "utf-8");
    console.log("Summary loaded.");
  } else {
    console.log("Generating summary of past recaps...");
    pastRecapsSummary = await generateRecapSummary(pastRecaps);
    fs.writeFileSync(SUMMARY_FILE, pastRecapsSummary, "utf-8");
    console.log("Summary generated and saved to results/recapSummary.txt");
  }

  const recap = await generateWeeklyReport(
    allGamesData,
    pastRecapsSummary,
    week,
  );

  const OUTPUT_FILE = path.join(
    process.cwd(),
    "results",
    `weeklyRecap-${week}.json`,
  );
  const outputDir = path.dirname(OUTPUT_FILE);

  try {
    // Ensure the 'utils' directory exists
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }

    // Write the file synchronously
    fs.writeFileSync(OUTPUT_FILE, JSON.stringify(recap), "utf8");
    console.log(`Successfully generated: ${OUTPUT_FILE}`);
  } catch (err) {
    console.error("Error writing games.generated.ts file:", err);
  }
}

async function makeDiscordAnnouncement(allGamesData: match[]) {
  const week = Math.max(...allGamesData.map((game) => game.week));
  const pastRecaps = loadAllRecaps();
  const recap = await generateDiscordAnnouncement(
    allGamesData,
    pastRecaps,
    week,
  );
  const OUTPUT_FILE = path.join(
    process.cwd(),
    "results",
    `discordAnnouncement.md`,
  );
  const outputDir = path.dirname(OUTPUT_FILE);

  try {
    // Ensure the 'utils' directory exists
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }

    // Write the file synchronously
    fs.writeFileSync(OUTPUT_FILE, recap.replace(/\n/g, "\r\n"), "utf8");
    console.log(`Successfully generated: ${OUTPUT_FILE}`);
  } catch (err) {
    console.error("Error writing games.generated.ts file:", err);
  }
}

async function makePopularityPost(allGamesData: match[]) {
  const week = Math.max(...allGamesData.map((game) => game.week));
  const pastRecaps = loadAllRecaps();
  const recap = await generatePopularityPost(allGamesData, pastRecaps, week);
  const OUTPUT_FILE = path.join(
    process.cwd(),
    "results",
    `popularityAnnouncement.md`,
  );
  const outputDir = path.dirname(OUTPUT_FILE);

  try {
    // Ensure the 'utils' directory exists
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }

    // Write the file synchronously
    fs.writeFileSync(OUTPUT_FILE, recap.replace(/\n/g, "\r\n"), "utf8");
    console.log(`Successfully generated: ${OUTPUT_FILE}`);
  } catch (err) {
    console.error("Error writing games.generated.ts file:", err);
  }
}

async function makeCelebrityPost(allGamesData: match[]) {
  const week = Math.max(...allGamesData.map((game) => game.week));
  const pastRecaps = loadAllRecaps();
  const recap = await generateCelebrityPost(pastRecaps);
  const OUTPUT_FILE = path.join(process.cwd(), "results", `celebrityPost.json`);
  const outputDir = path.dirname(OUTPUT_FILE);

  try {
    // Ensure the 'utils' directory exists
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }

    // Write the file synchronously
    fs.writeFileSync(OUTPUT_FILE, JSON.stringify(recap), "utf8");
    console.log(`Successfully generated: ${OUTPUT_FILE}`);
  } catch (err) {
    console.error("Error writing games.generated.ts file:", err);
  }
}

// --- Main Execution ---
const run = async () => {
  const allGamesData = generateGamesTS();
  const week = Math.max(...allGamesData.map((game) => game.week));

  const trimmedGamesData = allGamesData.map((game) => {
    const trimmedGame = game;
    if (trimmedGame.week !== week) {
      trimmedGame.preGame = "";
      trimmedGame.postGame = "";
    }

    const simplifyPlayers = (players: any[]) => {
      return players.map((p) => ({
        name: p.name,
        stats: {
          pregame_ritual: p.stats.pregame_ritual,
          pronouns: p.stats.pronouns,
        },
      }));
    };

    if ("players" in trimmedGame.awayTeam) {
      (trimmedGame.awayTeam as any).players = simplifyPlayers(
        (trimmedGame.awayTeam as any).players,
      );
    }
    if ("players" in trimmedGame.homeTeam) {
      (trimmedGame.homeTeam as any).players = simplifyPlayers(
        (trimmedGame.homeTeam as any).players,
      );
    }

    // aggressive delete
    delete (trimmedGame.homeTeam as any).activePlayers;
    delete (trimmedGame.homeTeam as any).inactivePlayers;
    delete (trimmedGame.awayTeam as any).activePlayers;
    delete (trimmedGame.awayTeam as any).inactivePlayers;

    return trimmedGame;
  });

  writeGeneratedTSFile(allGamesData);
  // await makeCelebrityPost(trimmedGamesData);
  // makeWeeklyRecap(trimmedGamesData);

  // makeDiscordAnnouncement(trimmedGamesData);
  // await makePopularityPost(trimmedGamesData);
};

run();
