import { TEAMS } from "../teams"; // Adjust path to your TEAMS file
import { team } from "@/utils/types"; // Adjust path to your consts file
import { seededShuffle } from "../utils";

/**
 * Defines the structure for a pre-season match.
 * It's based on your 'match' type but omits fields
 * that are generated by the gameRunner.
 */
interface BaseMatch {
  homeTeam: team;
  awayTeam: team;
  week: number;
}

/**
 * Generates a full round-robin (everyone plays everyone once)
 * league schedule.
 *
 * @param teams An object of all teams in the league, keyed by team name.
 * @returns An array of BaseMatch objects representing the full season.
 */
export function generateSeasonSchedule(
  teamRecord: Record<string, team>
): BaseMatch[] {
  const schedule: BaseMatch[] = [];
  const teamObjects = seededShuffle(Object.values(teamRecord), "Season 1");

  let teams = [...teamObjects];

  const numTeams = teams.length;
  const numWeeks = numTeams - 1;
  const gamesPerWeek = numTeams / 2;

  // Keep the first team fixed and rotate the rest
  const rotatingTeams = teams.slice(1);

  for (let week = 0; week < numWeeks; week++) {
    const team1 = teams[0];
    const team2 = rotatingTeams[0];

    // --- Game 1 (The fixed team's game) ---
    // We alternate home/away for the fixed team
    schedule.push({
      homeTeam: week % 2 === 0 ? team1 : team2,
      awayTeam: week % 2 === 0 ? team2 : team1,
      week: week,
    });

    // --- Other Games ---
    // Pair the remaining teams from the rotating list
    for (let i = 1; i < gamesPerWeek; i++) {
      const home = rotatingTeams[i];
      const away = rotatingTeams[rotatingTeams.length - i];

      schedule.push({
        homeTeam: home,
        awayTeam: away,
        week: week,
      });
    }

    // --- Rotate ---
    // Move the last team in the rotating list to the front
    const lastTeam = rotatingTeams.pop();

    if (lastTeam) {
      rotatingTeams.unshift(lastTeam);
    }
  }

  return schedule;
}

// --- EXPORT THE GENERATED SCHEDULE ---
// This is the array you can import into your gameRunner
export const LEAGUE_SCHEDULE: BaseMatch[] = generateSeasonSchedule(TEAMS);

/*
// --- How to use this in your gameRunner ---
// 
// import { LEAGUE_SCHEDULE } from './seasonGenerator';
// import { runGame } from './gameRunnerLogic'; // Assuming you have this
// import { match } from '../consts';
// 
// const fullSeasonResults: match[] = LEAGUE_SCHEDULE.map(baseMatch => {
//   
//   // Run the game simulation
//   const gameResult = runGame(baseMatch.homeTeam, baseMatch.awayTeam);
//   
//   // Combine the base match info with the result
//   return {
//     ...baseMatch,
//     homeScore: gameResult.homeScore,
//     awayScore: gameResult.awayScore,
//     preGame: gameResult.preGame,
//     postGame: gameResult.postGame,
//     // ... any other fields
//   };
// });
// 
// // Now you can write `fullSeasonResults` to your GAMES.ts file
// console.log(fullSeasonResults);
// 
*/
