import { team } from "./consts";

export enum TEAM_NAMES {
  "No Team" = "No Team",
  "The Tortell Privateers" = "The Tortell Privateers",
  "The South Pole Yetis" = "The South Pole Yetis",
  "The Confluence Captains" = "The Confluence Captains",
  "The New Prosperity Profits" = "The New Prosperity Profits",
  "The Southport Narwhals" = "The Southport Narwhals",
  "The New Ravenfall Commanders" = "The New Ravenfall Commanders",
  "The Brimstone Fire Eaters" = "The Brimstone Fire Eaters",
  "The Zmeigorod Snessengers" = "The Zmeigorod Snessengers",
  "The Haven Lights" = "The Haven Lights",
  "The Desert Spectres" = "The Desert Spectres",
  "The Ebon Gate Corruptors" = "The Ebon Gate Corruptors",
  "The Wyrmwood Stronghammers" = "The Wyrmwood Stronghammers",
  "The New Monteforte Chaos Creatures" = "The New Monteforte Chaos Creatures",
  "The Kerlauger Runeguard" = "The Kerlauger Runeguard",
  "The Starlight Bazaar Bizarres" = "The Starlight Bazaar Bizarres",
  "The Oread's Summit Tamers" = "The Oread's Summit Tamers",
}

export const TEAMS = {
  [TEAM_NAMES["The Brimstone Fire Eaters"]]: {
    name: "The Brimstone Fire Eaters",
    slug: "brimstone",
    losses: 0,
    wins: 0,
    score: 0,
    luck: 53,
    stadium: {
      name: "The Foundry Yard",
      location: "Brimstone",
      description:
        "Located in the industrial heart of the city, this stadium is perpetually covered in a layer of soot. The air is thick with smog from the surrounding smithies and forges.",
      modifiers: ["Industrial Smog", "Soot-Stained Ball", "Guild Riot"],
    },
    healer: {
      name: "Raphael Miyasawa",
      team: "The Brimstone Fire Eaters",
      stats: {
        pass: 46,
        catch: 49,
        run: 63,
        block: 56,
        fight: 60,
        throw: 60,
        luck: 63,
        pronouns: "She/Them",
        civic_engagement: 58,
        alcohol_tolerance: 56,
        favorite_weapon: "Cestus",
        pregame_ritual:
          "Kissing their biceps and whispering words of encouragement to them.",
        literate: true,
      },
    },
    players: [
      {
        name: "Bollinger Susette",
        team: "The Brimstone Fire Eaters",
        stats: {
          pass: 59,
          catch: 52,
          run: 46,
          block: 47,
          fight: 42,
          throw: 53,
          luck: 50,
          pronouns: "He/Him",
          civic_engagement: 56,
          alcohol_tolerance: 60,
          favorite_weapon: "Hatchet",
          pregame_ritual:
            "Getting a teammate to punch them in the shoulder, hard.",
          literate: true,
        },
      },
      {
        name: "Nachison Icken",
        team: "The Brimstone Fire Eaters",
        stats: {
          pass: 61,
          catch: 55,
          run: 43,
          block: 52,
          fight: 50,
          throw: 46,
          luck: 47,
          pronouns: "She/Them",
          civic_engagement: 42,
          alcohol_tolerance: 57,
          favorite_weapon: "Claymore",
          pregame_ritual:
            "Wearing their boots on the wrong feet during the warm-up.",
          literate: true,
        },
      },
      {
        name: "Glassman Solley",
        team: "The Brimstone Fire Eaters",
        stats: {
          pass: 54,
          catch: 50,
          run: 69,
          block: 62,
          fight: 58,
          throw: 42,
          luck: 53,
          pronouns: "He/Them",
          civic_engagement: 53,
          alcohol_tolerance: 55,
          favorite_weapon: "Rondel Dagger",
          pregame_ritual: "Washing their hands with dirt.",
          literate: false,
        },
      },
      {
        name: "Wylde Jutta",
        team: "The Brimstone Fire Eaters",
        stats: {
          pass: 63,
          catch: 61,
          run: 61,
          block: 49,
          fight: 67,
          throw: 51,
          luck: 52,
          pronouns: "She/Them",
          civic_engagement: 66,
          alcohol_tolerance: 52,
          favorite_weapon: "Voulge",
          pregame_ritual:
            "Asking a teammate to tell them a story, but only the beginning.",
          literate: true,
        },
      },
      {
        name: "Selimah Tully",
        team: "The Brimstone Fire Eaters",
        stats: {
          pass: 57,
          catch: 54,
          run: 57,
          block: 60,
          fight: 52,
          throw: 53,
          luck: 48,
          pronouns: "He/Him",
          civic_engagement: 61,
          alcohol_tolerance: 58,
          favorite_weapon: "Dagger",
          pregame_ritual: "Asking the referee to bless their weapon.",
          literate: false,
        },
      },
      {
        name: "Campball Fink",
        team: "The Brimstone Fire Eaters",
        stats: {
          pass: 56,
          catch: 60,
          run: 51,
          block: 61,
          fight: 66,
          throw: 43,
          luck: 61,
          pronouns: "She/Them",
          civic_engagement: 57,
          alcohol_tolerance: 55,
          favorite_weapon: "Swordstaff",
          pregame_ritual:
            "Finding the muddiest puddle and stomping in it with bare feet.",
          literate: false,
        },
      },
      {
        name: "Lowson Hersh",
        team: "The Brimstone Fire Eaters",
        stats: {
          pass: 58,
          catch: 43,
          run: 49,
          block: 44,
          fight: 48,
          throw: 60,
          luck: 58,
          pronouns: "They/Them",
          civic_engagement: 59,
          alcohol_tolerance: 63,
          favorite_weapon: "Spiked Gauntlet",
          pregame_ritual:
            "Staring at a single blade of grass until their eyes water.",
          literate: false,
        },
      },
      {
        name: "Oona Jane",
        team: "The Brimstone Fire Eaters",
        stats: {
          pass: 42,
          catch: 55,
          run: 58,
          block: 46,
          fight: 51,
          throw: 55,
          luck: 46,
          pronouns: "She/Her",
          civic_engagement: 57,
          alcohol_tolerance: 53,
          favorite_weapon: "Cudgel",
          pregame_ritual: "Wiping a teammate's sweat onto their own forehead.",
          literate: true,
        },
      },
      {
        name: "Orlina Jerrine",
        team: "The Brimstone Fire Eaters",
        stats: {
          pass: 61,
          catch: 57,
          run: 57,
          block: 50,
          fight: 54,
          throw: 52,
          luck: 49,
          pronouns: "He/Him",
          civic_engagement: 50,
          alcohol_tolerance: 45,
          favorite_weapon: "Rapier",
          pregame_ritual: "Attempting to communicate with birds.",
          literate: true,
        },
      },
      {
        name: "Nigel Rothmuller",
        team: "The Brimstone Fire Eaters",
        stats: {
          pass: 58,
          catch: 60,
          run: 56,
          block: 52,
          fight: 43,
          throw: 59,
          luck: 62,
          pronouns: "They/Them",
          civic_engagement: 52,
          alcohol_tolerance: 57,
          favorite_weapon: "Spear",
          pregame_ritual:
            "Consulting a folk rhyme about the weather to predict the game's outcome.",
          literate: true,
        },
      },
    ],
  },
  [TEAM_NAMES["The Confluence Captains"]]: {
    name: "The Confluence Captains",
    slug: "confluence",
    losses: 0,
    wins: 0,
    score: 0,
    luck: 60,
    stadium: {
      name: "The Captains' Green",
      location: "Confluence",
      description:
        "A prestigious field on a large island where the city's great rivers meet. While the pitch is pristine, it's surrounded by the noise of the river trade and the judgment of the city's elites.",
      modifiers: ["River Fog", "Toll Dispute", "Hometown Politics"],
    },
    healer: {
      name: "Kant Langill",
      team: "The Confluence Captains",
      stats: {
        pass: 51,
        catch: 55,
        run: 54,
        block: 49,
        fight: 59,
        throw: 59,
        luck: 65,
        pronouns: "He/Him",
        civic_engagement: 68,
        alcohol_tolerance: 65,
        favorite_weapon: "Scimitar",
        pregame_ritual:
          "Doing a terrible, clumsy dance to 'loosen the joints'.",
        literate: true,
      },
    },
    players: [
      {
        name: "Ladew Evelina",
        team: "The Confluence Captains",
        stats: {
          pass: 56,
          catch: 65,
          run: 58,
          block: 63,
          fight: 65,
          throw: 64,
          luck: 71,
          pronouns: "She/Them",
          civic_engagement: 46,
          alcohol_tolerance: 56,
          favorite_weapon: "Axe",
          pregame_ritual: "Chugging a raw egg, shell and all.",
          literate: true,
        },
      },
      {
        name: "Deach Sharlene",
        team: "The Confluence Captains",
        stats: {
          pass: 56,
          catch: 55,
          run: 52,
          block: 52,
          fight: 52,
          throw: 56,
          luck: 62,
          pronouns: "He/Them",
          civic_engagement: 52,
          alcohol_tolerance: 60,
          favorite_weapon: "Rapier",
          pregame_ritual:
            "Wearing their boots on the wrong feet during the warm-up.",
          literate: false,
        },
      },
      {
        name: "Stephan Lisk",
        team: "The Confluence Captains",
        stats: {
          pass: 60,
          catch: 57,
          run: 55,
          block: 59,
          fight: 60,
          throw: 56,
          luck: 51,
          pronouns: "He/Him",
          civic_engagement: 57,
          alcohol_tolerance: 58,
          favorite_weapon: "Pollaxe",
          pregame_ritual:
            "Arm-wrestling the player who plays the same position on their team.",
          literate: true,
        },
      },
      {
        name: "O'Conner Maighdlin",
        team: "The Confluence Captains",
        stats: {
          pass: 56,
          catch: 66,
          run: 66,
          block: 60,
          fight: 62,
          throw: 54,
          luck: 59,
          pronouns: "He/Him",
          civic_engagement: 62,
          alcohol_tolerance: 57,
          favorite_weapon: "Hatchet",
          pregame_ritual:
            "Speaking only in rhymes for the hour before the game.",
          literate: true,
        },
      },
      {
        name: "Belding Chloe",
        team: "The Confluence Captains",
        stats: {
          pass: 53,
          catch: 65,
          run: 62,
          block: 72,
          fight: 58,
          throw: 61,
          luck: 42,
          pronouns: "She/Her",
          civic_engagement: 57,
          alcohol_tolerance: 47,
          favorite_weapon: "Lance",
          pregame_ritual: "Rubbing the Trollball on their armpits for 'grip'.",
          literate: true,
        },
      },
      {
        name: "Behl Berstine",
        team: "The Confluence Captains",
        stats: {
          pass: 61,
          catch: 58,
          run: 65,
          block: 59,
          fight: 42,
          throw: 58,
          luck: 52,
          pronouns: "They/Them",
          civic_engagement: 53,
          alcohol_tolerance: 49,
          favorite_weapon: "Axe",
          pregame_ritual:
            "Wearing their boots on the wrong feet during the warm-up.",
          literate: false,
        },
      },
      {
        name: "Caves Cestar",
        team: "The Confluence Captains",
        stats: {
          pass: 54,
          catch: 52,
          run: 63,
          block: 50,
          fight: 60,
          throw: 55,
          luck: 66,
          pronouns: "He/Him",
          civic_engagement: 57,
          alcohol_tolerance: 54,
          favorite_weapon: "Maul",
          pregame_ritual:
            "Going over the game plan drawn in the dirt with the team captain.",
          literate: false,
        },
      },
      {
        name: "Vonni Geoff",
        team: "The Confluence Captains",
        stats: {
          pass: 60,
          catch: 62,
          run: 57,
          block: 51,
          fight: 49,
          throw: 49,
          luck: 58,
          pronouns: "He/Him",
          civic_engagement: 67,
          alcohol_tolerance: 65,
          favorite_weapon: "Sap",
          pregame_ritual:
            "Covering their forearms in a sticky tree sap for 'grip'.",
          literate: false,
        },
      },
      {
        name: "Carnahan Laud",
        team: "The Confluence Captains",
        stats: {
          pass: 46,
          catch: 63,
          run: 73,
          block: 49,
          fight: 59,
          throw: 53,
          luck: 60,
          pronouns: "She/Her",
          civic_engagement: 62,
          alcohol_tolerance: 68,
          favorite_weapon: "Lance",
          pregame_ritual: "Eating a dandelion, stem and all.",
          literate: false,
        },
      },
      {
        name: "Richia Pazit",
        team: "The Confluence Captains",
        stats: {
          pass: 61,
          catch: 42,
          run: 57,
          block: 55,
          fight: 45,
          throw: 50,
          luck: 59,
          pronouns: "They/Them",
          civic_engagement: 55,
          alcohol_tolerance: 55,
          favorite_weapon: "Pike",
          pregame_ritual: "Headbutting their own team's goal post (gently).",
          literate: true,
        },
      },
    ],
  },
  [TEAM_NAMES["The Desert Spectres"]]: {
    name: "The Desert Spectres",
    slug: "desert",
    losses: 0,
    wins: 0,
    score: 0,
    luck: 61,
    stadium: {
      name: "The Sun-Baked Bowl",
      location: "The Great Desert",
      description:
        "A simple, deep bowl dug from clay and sandstone on the edge of a caravan oasis. The heat is oppressive, and the 'stands' are just blankets laid on the sun-baked dunes.",
      modifiers: ["Intense Heat", "Sandstorm", "Dehydration"],
    },
    healer: {
      name: "Verlee Dacia",
      team: "The Desert Spectres",
      stats: {
        pass: 54,
        catch: 53,
        run: 68,
        block: 50,
        fight: 40,
        throw: 47,
        luck: 57,
        pronouns: "She/Her",
        civic_engagement: 60,
        alcohol_tolerance: 66,
        favorite_weapon: "Billhook",
        pregame_ritual:
          "Eating a piece of honeycomb to 'sweeten' their victory.",
        literate: true,
      },
    },
    players: [
      {
        name: "Fidellia Mozelle",
        team: "The Desert Spectres",
        stats: {
          pass: 40,
          catch: 57,
          run: 60,
          block: 56,
          fight: 65,
          throw: 67,
          luck: 57,
          pronouns: "She/Them",
          civic_engagement: 56,
          alcohol_tolerance: 60,
          favorite_weapon: "Swordstaff",
          pregame_ritual: "Smelling a piece of burnt wood from a campfire.",
          literate: false,
        },
      },
      {
        name: "Muscolo Jaehne",
        team: "The Desert Spectres",
        stats: {
          pass: 58,
          catch: 50,
          run: 53,
          block: 39,
          fight: 60,
          throw: 53,
          luck: 49,
          pronouns: "They/Them",
          civic_engagement: 46,
          alcohol_tolerance: 54,
          favorite_weapon: "Seax",
          pregame_ritual:
            "Methodically tearing a large leaf into tiny, identical pieces.",
          literate: false,
        },
      },
      {
        name: "Eileen Mikihisa",
        team: "The Desert Spectres",
        stats: {
          pass: 45,
          catch: 54,
          run: 59,
          block: 60,
          fight: 55,
          throw: 55,
          luck: 57,
          pronouns: "He/Him",
          civic_engagement: 51,
          alcohol_tolerance: 51,
          favorite_weapon: "Longsword",
          pregame_ritual:
            "Trying to teach a stray dog a complicated and useless new trick.",
          literate: false,
        },
      },
      {
        name: "Bahr Ethelstan",
        team: "The Desert Spectres",
        stats: {
          pass: 62,
          catch: 61,
          run: 62,
          block: 49,
          fight: 60,
          throw: 52,
          luck: 53,
          pronouns: "They/Them",
          civic_engagement: 59,
          alcohol_tolerance: 53,
          favorite_weapon: "Blackjack",
          pregame_ritual: "Humming a tune they believe only they know.",
          literate: false,
        },
      },
      {
        name: "Heyes Iver",
        team: "The Desert Spectres",
        stats: {
          pass: 55,
          catch: 60,
          run: 61,
          block: 51,
          fight: 54,
          throw: 71,
          luck: 49,
          pronouns: "He/Him",
          civic_engagement: 67,
          alcohol_tolerance: 48,
          favorite_weapon: "Woodsman's Axe",
          pregame_ritual: "Tugging on their left earlobe three times.",
          literate: false,
        },
      },
      {
        name: "Angelita Darce",
        team: "The Desert Spectres",
        stats: {
          pass: 52,
          catch: 50,
          run: 58,
          block: 53,
          fight: 56,
          throw: 58,
          luck: 58,
          pronouns: "He/Him",
          civic_engagement: 62,
          alcohol_tolerance: 65,
          favorite_weapon: "Bardiche",
          pregame_ritual:
            "Shaving one half of their mustache for important games.",
          literate: true,
        },
      },
      {
        name: "Shelman McQuoid",
        team: "The Desert Spectres",
        stats: {
          pass: 58,
          catch: 50,
          run: 53,
          block: 44,
          fight: 54,
          throw: 65,
          luck: 65,
          pronouns: "He/Them",
          civic_engagement: 64,
          alcohol_tolerance: 56,
          favorite_weapon: "Pike",
          pregame_ritual:
            "Consulting a folk rhyme about the weather to predict the game's outcome.",
          literate: true,
        },
      },
      {
        name: "Lovash Marius",
        team: "The Desert Spectres",
        stats: {
          pass: 52,
          catch: 46,
          run: 42,
          block: 56,
          fight: 43,
          throw: 53,
          luck: 57,
          pronouns: "She/Them",
          civic_engagement: 59,
          alcohol_tolerance: 54,
          favorite_weapon: "War Pick",
          pregame_ritual:
            "Sticking a specific type of feather in their helmet's plume.",
          literate: true,
        },
      },
      {
        name: "Unni Schlicher",
        team: "The Desert Spectres",
        stats: {
          pass: 59,
          catch: 63,
          run: 55,
          block: 59,
          fight: 64,
          throw: 48,
          luck: 54,
          pronouns: "She/Her",
          civic_engagement: 42,
          alcohol_tolerance: 57,
          favorite_weapon: "Halberd",
          pregame_ritual:
            "Organizing a small betting pool on who will score first.",
          literate: true,
        },
      },
      {
        name: "Huesman Ring",
        team: "The Desert Spectres",
        stats: {
          pass: 48,
          catch: 56,
          run: 41,
          block: 48,
          fight: 58,
          throw: 38,
          luck: 44,
          pronouns: "He/Them",
          civic_engagement: 56,
          alcohol_tolerance: 58,
          favorite_weapon: "Military Fork",
          pregame_ritual:
            "Dipping their hands in a bucket of ice-cold well water.",
          literate: true,
        },
      },
    ],
  },
  [TEAM_NAMES["The Haven Lights"]]: {
    name: "The Haven Lights",
    slug: "haven",
    losses: 0,
    wins: 0,
    score: 0,
    luck: 55,
    stadium: {
      name: "The Beacon Green",
      location: "Haven",
      description:
        "A perfectly manicured field adjacent to the city's famed university, The Scholarium. The crowd is quiet, judgmental, and quick to criticize any perceived lack of sportsmanship.",
      modifiers: ["Scholarly Debate", "Harbor Bells", "Public Scrutiny"],
    },
    healer: {
      name: "Riffle Harrington",
      team: "The Haven Lights",
      stats: {
        pass: 56,
        catch: 49,
        run: 49,
        block: 43,
        fight: 66,
        throw: 52,
        luck: 63,
        pronouns: "He/Him",
        civic_engagement: 63,
        alcohol_tolerance: 52,
        favorite_weapon: "Spiked Gauntlet",
        pregame_ritual:
          "Tying their bootlaces together and hopping to the starting line.",
        literate: false,
      },
    },
    players: [
      {
        name: "Shiroma Salim",
        team: "The Haven Lights",
        stats: {
          pass: 50,
          catch: 51,
          run: 54,
          block: 55,
          fight: 54,
          throw: 62,
          luck: 55,
          pronouns: "He/Him",
          civic_engagement: 51,
          alcohol_tolerance: 60,
          favorite_weapon: "Kirkhammer",
          pregame_ritual: "Re-taping their shield's handle with fresh leather.",
          literate: true,
        },
      },
      {
        name: "Zwart Bunns",
        team: "The Haven Lights",
        stats: {
          pass: 63,
          catch: 66,
          run: 51,
          block: 51,
          fight: 47,
          throw: 50,
          luck: 53,
          pronouns: "He/Him",
          civic_engagement: 40,
          alcohol_tolerance: 55,
          favorite_weapon: "Cestus",
          pregame_ritual:
            "Whispering a secret fear to the Trollball before the game.",
          literate: false,
        },
      },
      {
        name: "Riffle Heyde",
        team: "The Haven Lights",
        stats: {
          pass: 55,
          catch: 56,
          run: 48,
          block: 53,
          fight: 50,
          throw: 44,
          luck: 48,
          pronouns: "They/Them",
          civic_engagement: 47,
          alcohol_tolerance: 51,
          favorite_weapon: "Mace",
          pregame_ritual: "Drinking a full waterskin of lukewarm water.",
          literate: true,
        },
      },
      {
        name: "Tybi Reo",
        team: "The Haven Lights",
        stats: {
          pass: 55,
          catch: 48,
          run: 66,
          block: 56,
          fight: 55,
          throw: 48,
          luck: 50,
          pronouns: "She/Them",
          civic_engagement: 63,
          alcohol_tolerance: 50,
          favorite_weapon: "Mace",
          pregame_ritual:
            "Drawing a detailed, anatomically incorrect diagram of a troll's head.",
          literate: false,
        },
      },
      {
        name: "Berkin Waters",
        team: "The Haven Lights",
        stats: {
          pass: 51,
          catch: 46,
          run: 58,
          block: 50,
          fight: 54,
          throw: 60,
          luck: 49,
          pronouns: "He/Him",
          civic_engagement: 55,
          alcohol_tolerance: 51,
          favorite_weapon: "Zweihander",
          pregame_ritual:
            "Passing a 'team luckstone' from player to player without speaking.",
          literate: true,
        },
      },
      {
        name: "Farand Keil",
        team: "The Haven Lights",
        stats: {
          pass: 57,
          catch: 49,
          run: 55,
          block: 37,
          fight: 50,
          throw: 64,
          luck: 48,
          pronouns: "He/Him",
          civic_engagement: 51,
          alcohol_tolerance: 61,
          favorite_weapon: "Whip",
          pregame_ritual:
            "Chewing a specific, bitter root said to improve night vision.",
          literate: true,
        },
      },
      {
        name: "Wieren Ivar",
        team: "The Haven Lights",
        stats: {
          pass: 66,
          catch: 63,
          run: 52,
          block: 54,
          fight: 64,
          throw: 42,
          luck: 54,
          pronouns: "He/Them",
          civic_engagement: 45,
          alcohol_tolerance: 56,
          favorite_weapon: "Warhammer",
          pregame_ritual:
            "Jogging three laps around the perimeter of the field.",
          literate: false,
        },
      },
      {
        name: "Coward Tarton",
        team: "The Haven Lights",
        stats: {
          pass: 56,
          catch: 51,
          run: 62,
          block: 47,
          fight: 52,
          throw: 63,
          luck: 51,
          pronouns: "She/Her",
          civic_engagement: 60,
          alcohol_tolerance: 63,
          favorite_weapon: "Tabar",
          pregame_ritual:
            "Kissing their biceps and whispering words of encouragement to them.",
          literate: false,
        },
      },
      {
        name: "Dickenson Beker",
        team: "The Haven Lights",
        stats: {
          pass: 58,
          catch: 69,
          run: 58,
          block: 53,
          fight: 52,
          throw: 46,
          luck: 63,
          pronouns: "She/Her",
          civic_engagement: 52,
          alcohol_tolerance: 58,
          favorite_weapon: "Billhook",
          pregame_ritual:
            "Trying to teach a stray dog a complicated and useless new trick.",
          literate: true,
        },
      },
      {
        name: "Marlane Lounge",
        team: "The Haven Lights",
        stats: {
          pass: 64,
          catch: 59,
          run: 54,
          block: 53,
          fight: 52,
          throw: 52,
          luck: 58,
          pronouns: "They/Them",
          civic_engagement: 55,
          alcohol_tolerance: 59,
          favorite_weapon: "Main-gauche",
          pregame_ritual:
            "Challenging a spectator to a game of tic-tac-toe in the dirt.",
          literate: false,
        },
      },
    ],
  },
  [TEAM_NAMES["The Ebon Gate Corruptors"]]: {
    name: "The Ebon Gate Corruptors",
    slug: "ebon-gate",
    losses: 0,
    wins: 0,
    score: 0,
    luck: 59,
    stadium: {
      name: "The Sinking Field",
      location: "Ebon Gate",
      description:
        "A notoriously poorly-maintained stadium built on reclaimed marshland. The ground is unstable, often waterlogged, and sections of the stands are known to collapse.",
      modifiers: ["Thick Mud", "Noxious Fumes", "Sinkhole"],
    },
    healer: {
      name: "Terle Chenay",
      team: "The Ebon Gate Corruptors",
      stats: {
        pass: 62,
        catch: 64,
        run: 70,
        block: 58,
        fight: 46,
        throw: 62,
        luck: 58,
        pronouns: "She/Her",
        civic_engagement: 55,
        alcohol_tolerance: 54,
        favorite_weapon: "Mace",
        pregame_ritual: "Seeing who on the team can belch the loudest.",
        literate: false,
      },
    },
    players: [
      {
        name: "Bullion Iglesias",
        team: "The Ebon Gate Corruptors",
        stats: {
          pass: 51,
          catch: 62,
          run: 55,
          block: 52,
          fight: 52,
          throw: 62,
          luck: 57,
          pronouns: "He/Them",
          civic_engagement: 57,
          alcohol_tolerance: 52,
          favorite_weapon: "Axe",
          pregame_ritual:
            "Meditating silently in the corner of the locker room.",
          literate: true,
        },
      },
      {
        name: "Olnek Vizzone",
        team: "The Ebon Gate Corruptors",
        stats: {
          pass: 54,
          catch: 48,
          run: 53,
          block: 59,
          fight: 49,
          throw: 63,
          luck: 52,
          pronouns: "He/Him",
          civic_engagement: 57,
          alcohol_tolerance: 52,
          favorite_weapon: "Sickle",
          pregame_ritual: "Clapping their hands a prime number of times.",
          literate: true,
        },
      },
      {
        name: "As Utter",
        team: "The Ebon Gate Corruptors",
        stats: {
          pass: 56,
          catch: 57,
          run: 48,
          block: 50,
          fight: 67,
          throw: 38,
          luck: 51,
          pronouns: "He/Him",
          civic_engagement: 70,
          alcohol_tolerance: 61,
          favorite_weapon: "Greatsword",
          pregame_ritual:
            "Insisting on being the last player to leave the locker room.",
          literate: true,
        },
      },
      {
        name: "Smith Syst",
        team: "The Ebon Gate Corruptors",
        stats: {
          pass: 51,
          catch: 59,
          run: 49,
          block: 47,
          fight: 63,
          throw: 59,
          luck: 52,
          pronouns: "She/Her",
          civic_engagement: 54,
          alcohol_tolerance: 51,
          favorite_weapon: "Voulge",
          pregame_ritual: "Daring a teammate to eat a live worm.",
          literate: true,
        },
      },
      {
        name: "Napoleon Anzovin",
        team: "The Ebon Gate Corruptors",
        stats: {
          pass: 50,
          catch: 63,
          run: 52,
          block: 45,
          fight: 59,
          throw: 49,
          luck: 57,
          pronouns: "He/Him",
          civic_engagement: 57,
          alcohol_tolerance: 58,
          favorite_weapon: "Kirkhammer",
          pregame_ritual:
            "Thanking their armor for the protection it's about to offer.",
          literate: true,
        },
      },
      {
        name: "Simsar Carrelli",
        team: "The Ebon Gate Corruptors",
        stats: {
          pass: 68,
          catch: 54,
          run: 53,
          block: 56,
          fight: 53,
          throw: 49,
          luck: 68,
          pronouns: "He/Him",
          civic_engagement: 63,
          alcohol_tolerance: 56,
          favorite_weapon: "Billhook",
          pregame_ritual: "Counting the number of clouds in the sky.",
          literate: true,
        },
      },
      {
        name: "Ahasuerus An",
        team: "The Ebon Gate Corruptors",
        stats: {
          pass: 39,
          catch: 56,
          run: 49,
          block: 61,
          fight: 51,
          throw: 63,
          luck: 55,
          pronouns: "She/Them",
          civic_engagement: 55,
          alcohol_tolerance: 64,
          favorite_weapon: "Talwar",
          pregame_ritual:
            "Tapping each piece of their armor in a specific sequence.",
          literate: false,
        },
      },
      {
        name: "Ellette Paz",
        team: "The Ebon Gate Corruptors",
        stats: {
          pass: 54,
          catch: 49,
          run: 54,
          block: 65,
          fight: 54,
          throw: 66,
          luck: 44,
          pronouns: "She/Them",
          civic_engagement: 51,
          alcohol_tolerance: 54,
          favorite_weapon: "Blackjack",
          pregame_ritual:
            "Insisting on being the last player to leave the locker room.",
          literate: false,
        },
      },
      {
        name: "Judi Carrington",
        team: "The Ebon Gate Corruptors",
        stats: {
          pass: 61,
          catch: 53,
          run: 58,
          block: 53,
          fight: 55,
          throw: 56,
          luck: 45,
          pronouns: "He/Him",
          civic_engagement: 54,
          alcohol_tolerance: 54,
          favorite_weapon: "Estoc",
          pregame_ritual: "Singing a sea shanty completely out of tune.",
          literate: true,
        },
      },
      {
        name: "Amedeo Bari",
        team: "The Ebon Gate Corruptors",
        stats: {
          pass: 60,
          catch: 54,
          run: 67,
          block: 53,
          fight: 53,
          throw: 53,
          luck: 45,
          pronouns: "He/Him",
          civic_engagement: 46,
          alcohol_tolerance: 51,
          favorite_weapon: "Rapier",
          pregame_ritual: "Polishing their boots with bacon grease.",
          literate: false,
        },
      },
    ],
  },
  [TEAM_NAMES["The Kerlauger Runeguard"]]: {
    name: "The Kerlauger Runeguard",
    slug: "kerlauger",
    losses: 0,
    wins: 0,
    score: 0,
    luck: 60,
    stadium: {
      name: "The Old Fort",
      location: "Kerlauger",
      description:
        "The team plays within the crumbling, stone-ringed ruins of an ancient hill-fort. The 'runes' are just old, weathered carvings on the standing stones that serve as obstacles.",
      modifiers: ["Ancient Ruins", "Dense Fog", "Uneven Footing"],
    },
    healer: {
      name: "Eal Caundra",
      team: "The Kerlauger Runeguard",
      stats: {
        pass: 63,
        catch: 55,
        run: 51,
        block: 57,
        fight: 46,
        throw: 59,
        luck: 54,
        pronouns: "He/Them",
        civic_engagement: 45,
        alcohol_tolerance: 54,
        favorite_weapon: "War Scythe",
        pregame_ritual:
          "Reciting the names of legendary Trollball players of the past.",
        literate: true,
      },
    },
    players: [
      {
        name: "Lashondra Niehaus",
        team: "The Kerlauger Runeguard",
        stats: {
          pass: 62,
          catch: 55,
          run: 57,
          block: 58,
          fight: 62,
          throw: 48,
          luck: 57,
          pronouns: "She/Her",
          civic_engagement: 67,
          alcohol_tolerance: 50,
          pregame_ritual:
            "Getting a teammate to punch them in the shoulder, hard.",
          literate: true,
        },
      },
      {
        name: "Reginauld Cordell",
        team: "The Kerlauger Runeguard",
        stats: {
          pass: 50,
          catch: 55,
          run: 65,
          block: 58,
          fight: 51,
          throw: 55,
          luck: 58,
          pronouns: "He/Them",
          civic_engagement: 50,
          alcohol_tolerance: 36,
          favorite_weapon: "Main-gauche",
          pregame_ritual:
            "Tracing an invisible, complex sigil over their heart.",
          literate: false,
        },
      },
      {
        name: "Benjie Foulk",
        team: "The Kerlauger Runeguard",
        stats: {
          pass: 50,
          catch: 63,
          run: 54,
          block: 58,
          fight: 51,
          throw: 54,
          luck: 59,
          pronouns: "She/Her",
          civic_engagement: 55,
          alcohol_tolerance: 46,
          favorite_weapon: "Axe",
          pregame_ritual:
            "Patting every beast of burden they see on the way to the match.",
          literate: false,
        },
      },
      {
        name: "Johnna Beetner",
        team: "The Kerlauger Runeguard",
        stats: {
          pass: 68,
          catch: 60,
          run: 69,
          block: 56,
          fight: 43,
          throw: 49,
          luck: 54,
          pronouns: "She/Her",
          civic_engagement: 51,
          alcohol_tolerance: 49,
          favorite_weapon: "Scimitar",
          pregame_ritual:
            "Collecting a pebble from every field they've ever played on.",
          literate: false,
        },
      },
      {
        name: "Harilda Sigsmond",
        team: "The Kerlauger Runeguard",
        stats: {
          pass: 58,
          catch: 56,
          run: 65,
          block: 59,
          fight: 51,
          throw: 60,
          luck: 65,
          pronouns: "He/Them",
          civic_engagement: 49,
          alcohol_tolerance: 51,
          favorite_weapon: "Battle Axe",
          pregame_ritual:
            "Leading the team in a synchronized chant that slowly gets louder.",
          literate: true,
        },
      },
      {
        name: "Vivia Namara",
        team: "The Kerlauger Runeguard",
        stats: {
          pass: 59,
          catch: 53,
          run: 51,
          block: 57,
          fight: 50,
          throw: 59,
          luck: 49,
          pronouns: "She/Them",
          civic_engagement: 52,
          alcohol_tolerance: 46,
          favorite_weapon: "Great Axe",
          pregame_ritual:
            "Spitting into their own hand and then slapping their face with it.",
          literate: true,
        },
      },
      {
        name: "Lon Gabriell",
        team: "The Kerlauger Runeguard",
        stats: {
          pass: 56,
          catch: 41,
          run: 55,
          block: 67,
          fight: 53,
          throw: 61,
          luck: 55,
          pronouns: "She/Her",
          civic_engagement: 65,
          alcohol_tolerance: 48,
          favorite_weapon: "Lance",
          pregame_ritual:
            "Reciting the names of legendary Trollball players of the past.",
          literate: true,
        },
      },
      {
        name: "Shepperd Trefler",
        team: "The Kerlauger Runeguard",
        stats: {
          pass: 50,
          catch: 58,
          run: 59,
          block: 55,
          fight: 66,
          throw: 51,
          luck: 54,
          pronouns: "He/Him",
          civic_engagement: 47,
          alcohol_tolerance: 66,
          favorite_weapon: "Spiked Gauntlet",
          pregame_ritual: "Braiding their hair into tight, battle-ready rows.",
          literate: true,
        },
      },
      {
        name: "Gurney Fadiman",
        team: "The Kerlauger Runeguard",
        stats: {
          pass: 58,
          catch: 42,
          run: 52,
          block: 59,
          fight: 53,
          throw: 49,
          luck: 58,
          pronouns: "They/Them",
          civic_engagement: 52,
          alcohol_tolerance: 54,
          favorite_weapon: "Shortsword",
          pregame_ritual:
            "A toast of goat's milk to the health of their rivals.",
          literate: true,
        },
      },
      {
        name: "Lorilee Aldred",
        team: "The Kerlauger Runeguard",
        stats: {
          pass: 49,
          catch: 54,
          run: 55,
          block: 56,
          fight: 64,
          throw: 55,
          luck: 54,
          pronouns: "He/Them",
          civic_engagement: 49,
          alcohol_tolerance: 50,
          favorite_weapon: "Katar",
          pregame_ritual:
            "Sharing a ceremonial, non-alcoholic grog from a communal cup.",
          literate: true,
        },
      },
    ],
  },
  [TEAM_NAMES["The New Monteforte Chaos Creatures"]]: {
    name: "The New Monteforte Chaos Creatures",
    slug: "new-monteforte",
    losses: 0,
    wins: 0,
    score: 0,
    luck: 65,
    stadium: {
      name: "The Unruly Yard",
      location: "New Monteforte",
      description:
        "A field in the center of the city's most rebellious district. The stadium is covered in graffiti, the crowd is hostile, and riots are a common post-game (and mid-game) event.",
      modifiers: ["Rowdy Crowd", "Unstable Scaffolding", "Street Performer"],
    },
    healer: {
      name: "Lian Denton",
      team: "The New Monteforte Chaos Creatures",
      stats: {
        pass: 55,
        catch: 62,
        run: 56,
        block: 58,
        fight: 45,
        throw: 60,
        luck: 50,
        pronouns: "They/Them",
        civic_engagement: 52,
        alcohol_tolerance: 66,
        favorite_weapon: "Battle Axe",
        pregame_ritual: "Drinking a shot of hot gravy from a dented tin cup.",
        literate: false,
      },
    },
    players: [
      {
        name: "Boulanger Procto",
        team: "The New Monteforte Chaos Creatures",
        stats: {
          pass: 53,
          catch: 48,
          run: 57,
          block: 66,
          fight: 60,
          throw: 57,
          luck: 54,
          pronouns: "He/Him",
          civic_engagement: 49,
          alcohol_tolerance: 45,
          favorite_weapon: "Broadsword",
          pregame_ritual:
            "Arranging their gear in a perfect, aesthetically pleasing spiral.",
          literate: true,
        },
      },
      {
        name: "Urata Oriana",
        team: "The New Monteforte Chaos Creatures",
        stats: {
          pass: 46,
          catch: 42,
          run: 49,
          block: 49,
          fight: 52,
          throw: 54,
          luck: 50,
          pronouns: "He/Them",
          civic_engagement: 54,
          alcohol_tolerance: 56,
          favorite_weapon: "Zweihander",
          pregame_ritual:
            "Testing the heft of their weapon with a series of slow, deliberate swings.",
          literate: true,
        },
      },
      {
        name: "Gabriele Klehm",
        team: "The New Monteforte Chaos Creatures",
        stats: {
          pass: 59,
          catch: 57,
          run: 47,
          block: 62,
          fight: 50,
          throw: 56,
          luck: 55,
          pronouns: "She/Them",
          civic_engagement: 66,
          alcohol_tolerance: 50,
          favorite_weapon: "Quarterstaff",
          pregame_ritual: "Kissing the Trollball on its stitched 'nose'.",
          literate: true,
        },
      },
      {
        name: "Tucker Hett",
        team: "The New Monteforte Chaos Creatures",
        stats: {
          pass: 50,
          catch: 50,
          run: 49,
          block: 59,
          fight: 52,
          throw: 61,
          luck: 42,
          pronouns: "She/Them",
          civic_engagement: 46,
          alcohol_tolerance: 57,
          favorite_weapon: "Billhook",
          pregame_ritual: "Reviewing hand signals for secret plays.",
          literate: true,
        },
      },
      {
        name: "Mouldon Earl",
        team: "The New Monteforte Chaos Creatures",
        stats: {
          pass: 55,
          catch: 55,
          run: 63,
          block: 56,
          fight: 44,
          throw: 55,
          luck: 57,
          pronouns: "They/Them",
          civic_engagement: 51,
          alcohol_tolerance: 52,
          favorite_weapon: "Rondel Dagger",
          pregame_ritual:
            "Refusing to step on any lines on the field before the whistle blows.",
          literate: true,
        },
      },
      {
        name: "Placido Kora",
        team: "The New Monteforte Chaos Creatures",
        stats: {
          pass: 67,
          catch: 59,
          run: 48,
          block: 52,
          fight: 56,
          throw: 46,
          luck: 46,
          pronouns: "She/Her",
          civic_engagement: 47,
          alcohol_tolerance: 45,
          favorite_weapon: "Seax",
          pregame_ritual:
            "Telling a terrible joke to the Trollball to 'loosen it up'.",
          literate: true,
        },
      },
      {
        name: "Alben Diantha",
        team: "The New Monteforte Chaos Creatures",
        stats: {
          pass: 53,
          catch: 54,
          run: 48,
          block: 55,
          fight: 63,
          throw: 65,
          luck: 52,
          pronouns: "He/Him",
          civic_engagement: 52,
          alcohol_tolerance: 57,
          favorite_weapon: "Hammer",
          pregame_ritual:
            "Dipping their hands in a bucket of ice-cold well water.",
          literate: true,
        },
      },
      {
        name: "Fogel Raynold",
        team: "The New Monteforte Chaos Creatures",
        stats: {
          pass: 48,
          catch: 48,
          run: 54,
          block: 54,
          fight: 48,
          throw: 57,
          luck: 60,
          pronouns: "He/Them",
          civic_engagement: 61,
          alcohol_tolerance: 55,
          favorite_weapon: "Horseman's Pick",
          pregame_ritual: "Slapping their own helmet until their ears ring.",
          literate: true,
        },
      },
      {
        name: "Wolbrom Ariella",
        team: "The New Monteforte Chaos Creatures",
        stats: {
          pass: 63,
          catch: 71,
          run: 59,
          block: 40,
          fight: 60,
          throw: 58,
          luck: 72,
          pronouns: "He/Them",
          civic_engagement: 45,
          alcohol_tolerance: 53,
          favorite_weapon: "Scythe",
          pregame_ritual: "Singing a sea shanty completely out of tune.",
          literate: false,
        },
      },
      {
        name: "Raouf Dragone",
        team: "The New Monteforte Chaos Creatures",
        stats: {
          pass: 48,
          catch: 61,
          run: 52,
          block: 44,
          fight: 50,
          throw: 61,
          luck: 52,
          pronouns: "They/Them",
          civic_engagement: 63,
          alcohol_tolerance: 61,
          favorite_weapon: "Trident",
          pregame_ritual: "Reciting a short, epic poem about a past victory.",
          literate: false,
        },
      },
    ],
  },
  [TEAM_NAMES["The New Prosperity Profits"]]: {
    name: "The New Prosperity Profits",
    slug: "new-prosperity",
    losses: 0,
    wins: 0,
    score: 0,
    luck: 50,
    stadium: {
      name: "The Guilder's Field",
      location: "New Prosperity",
      description:
        "An opulent stadium sponsored by the powerful Merchant's Guild. The stands feature luxurious, velvet-lined boxes for bankers, who are often more focused on making deals than the game.",
      modifiers: ["Hostile Takeover", "Hired Hecklers", "Market Fluctuation"],
    },
    healer: {
      name: "Merissa Mathian",
      team: "The New Prosperity Profits",
      stats: {
        pass: 54,
        catch: 54,
        run: 53,
        block: 45,
        fight: 52,
        throw: 59,
        luck: 49,
        pronouns: "She/Her",
        civic_engagement: 66,
        alcohol_tolerance: 51,
        favorite_weapon: "Longsword",
        pregame_ritual: "Washing their hands with dirt.",
        literate: true,
      },
    },
    players: [
      {
        name: "Pulchi Benyamin",
        team: "The New Prosperity Profits",
        stats: {
          pass: 54,
          catch: 63,
          run: 67,
          block: 63,
          fight: 47,
          throw: 44,
          luck: 56,
          pronouns: "She/Them",
          civic_engagement: 59,
          alcohol_tolerance: 54,
          favorite_weapon: "Swordstaff",
          pregame_ritual: "Eating a dandelion, stem and all.",
          literate: true,
        },
      },
      {
        name: "Boleslaw Heathcote",
        team: "The New Prosperity Profits",
        stats: {
          pass: 60,
          catch: 48,
          run: 51,
          block: 58,
          fight: 48,
          throw: 47,
          luck: 56,
          pronouns: "She/Her",
          civic_engagement: 53,
          alcohol_tolerance: 56,
          favorite_weapon: "Zweihander",
          pregame_ritual:
            "Lighting a small piece of parchment on fire and inhaling the smoke.",
          literate: false,
        },
      },
      {
        name: "Gladdie Farika",
        team: "The New Prosperity Profits",
        stats: {
          pass: 48,
          catch: 48,
          run: 60,
          block: 54,
          fight: 58,
          throw: 59,
          luck: 51,
          pronouns: "They/Them",
          civic_engagement: 77,
          alcohol_tolerance: 62,
          favorite_weapon: "Morning Star",
          pregame_ritual:
            "Meticulously cleaning each stud on their boots with a special brush.",
          literate: true,
        },
      },
      {
        name: "Yoshi Cathy",
        team: "The New Prosperity Profits",
        stats: {
          pass: 47,
          catch: 50,
          run: 56,
          block: 60,
          fight: 74,
          throw: 57,
          luck: 58,
          pronouns: "He/Them",
          civic_engagement: 54,
          alcohol_tolerance: 50,
          favorite_weapon: "Spear",
          pregame_ritual: "Eating a raw onion, layer by layer, without crying.",
          literate: false,
        },
      },
      {
        name: "Aufmann Tedric",
        team: "The New Prosperity Profits",
        stats: {
          pass: 62,
          catch: 51,
          run: 61,
          block: 55,
          fight: 55,
          throw: 58,
          luck: 54,
          pronouns: "She/Them",
          civic_engagement: 62,
          alcohol_tolerance: 58,
          favorite_weapon: "Dane Axe",
          pregame_ritual:
            "Getting a teammate to pour a bucket of cold water over their head.",
          literate: true,
        },
      },
      {
        name: "Krueger Jacinthe",
        team: "The New Prosperity Profits",
        stats: {
          pass: 61,
          catch: 53,
          run: 49,
          block: 57,
          fight: 59,
          throw: 47,
          luck: 53,
          pronouns: "He/Him",
          civic_engagement: 44,
          alcohol_tolerance: 42,
          favorite_weapon: "Spear",
          pregame_ritual:
            "A team-wide moment of absolute silence to 'gather their thoughts'.",
          literate: false,
        },
      },
      {
        name: "Abramson Doxia",
        team: "The New Prosperity Profits",
        stats: {
          pass: 51,
          catch: 61,
          run: 53,
          block: 57,
          fight: 55,
          throw: 45,
          luck: 50,
          pronouns: "He/Them",
          civic_engagement: 66,
          alcohol_tolerance: 70,
          favorite_weapon: "Arming Sword",
          pregame_ritual:
            "Sharpening the edges of their blunted weapon (an exercise in futility).",
          literate: true,
        },
      },
      {
        name: "Milman Galvan",
        team: "The New Prosperity Profits",
        stats: {
          pass: 51,
          catch: 66,
          run: 56,
          block: 50,
          fight: 52,
          throw: 68,
          luck: 56,
          pronouns: "She/Them",
          civic_engagement: 60,
          alcohol_tolerance: 62,
          favorite_weapon: "Boar Spear",
          pregame_ritual: "Humming a tune they believe only they know.",
          literate: false,
        },
      },
      {
        name: "Faina Hendrix",
        team: "The New Prosperity Profits",
        stats: {
          pass: 52,
          catch: 55,
          run: 63,
          block: 67,
          fight: 53,
          throw: 57,
          luck: 56,
          pronouns: "He/Him",
          civic_engagement: 54,
          alcohol_tolerance: 65,
          favorite_weapon: "Greatsword",
          pregame_ritual:
            "Lighting a small piece of parchment on fire and inhaling the smoke.",
          literate: true,
        },
      },
      {
        name: "Pellikka Concettina",
        team: "The New Prosperity Profits",
        stats: {
          pass: 64,
          catch: 44,
          run: 58,
          block: 62,
          fight: 54,
          throw: 51,
          luck: 58,
          pronouns: "He/Him",
          civic_engagement: 53,
          alcohol_tolerance: 53,
          favorite_weapon: "Spear",
          pregame_ritual:
            "Avoiding eye contact with anyone wearing the color green.",
          literate: true,
        },
      },
    ],
  },
  [TEAM_NAMES["The New Ravenfall Commanders"]]: {
    name: "The New Ravenfall Commanders",
    slug: "new-ravenfall",
    losses: 0,
    wins: 0,
    score: 0,
    luck: 64,
    stadium: {
      name: "The Bailey",
      location: "New Ravenfall",
      description:
        "The team plays in the central training yard, or 'bailey', of the city's grim, black-stone fortress. The crowd watches from the ramparts, and the game is often interrupted by guard drills.",
      modifiers: ["Uneven Ground", "Watchtower Sentries", "Call to Arms"],
    },
    healer: {
      name: "Hooge Imtiaz",
      team: "The New Ravenfall Commanders",
      stats: {
        pass: 57,
        catch: 50,
        run: 39,
        block: 59,
        fight: 53,
        throw: 63,
        luck: 59,
        pronouns: "She/Her",
        civic_engagement: 56,
        alcohol_tolerance: 44,
        favorite_weapon: "Warhammer",
        pregame_ritual:
          "Leading the team in a synchronized chant that slowly gets louder.",
        literate: true,
      },
    },
    players: [
      {
        name: "Dusa Curson",
        team: "The New Ravenfall Commanders",
        stats: {
          pass: 47,
          catch: 52,
          run: 55,
          block: 56,
          fight: 59,
          throw: 41,
          luck: 57,
          pronouns: "She/Them",
          civic_engagement: 48,
          alcohol_tolerance: 51,
          favorite_weapon: "Hatchet",
          pregame_ritual:
            "Searching for a four-leaf clover near the sidelines.",
          literate: false,
        },
      },
      {
        name: "Moir Sass",
        team: "The New Ravenfall Commanders",
        stats: {
          pass: 58,
          catch: 50,
          run: 51,
          block: 48,
          fight: 60,
          throw: 56,
          luck: 61,
          pronouns: "They/Them",
          civic_engagement: 55,
          alcohol_tolerance: 53,
          favorite_weapon: "Trident",
          pregame_ritual: "Reciting a short, epic poem about a past victory.",
          literate: true,
        },
      },
      {
        name: "Theis Loredo",
        team: "The New Ravenfall Commanders",
        stats: {
          pass: 56,
          catch: 46,
          run: 55,
          block: 54,
          fight: 62,
          throw: 61,
          luck: 59,
          pronouns: "She/Them",
          civic_engagement: 49,
          alcohol_tolerance: 49,
          favorite_weapon: "Claymore",
          pregame_ritual: "Sharing a piece of fermented fish with a teammate.",
          literate: true,
        },
      },
      {
        name: "Nitz Alis",
        team: "The New Ravenfall Commanders",
        stats: {
          pass: 52,
          catch: 53,
          run: 52,
          block: 61,
          fight: 63,
          throw: 58,
          luck: 48,
          pronouns: "He/Him",
          civic_engagement: 57,
          alcohol_tolerance: 46,
          favorite_weapon: "Glaive",
          pregame_ritual:
            "Listening to the wind for a sign of which way the game will turn.",
          literate: true,
        },
      },
      {
        name: "Estes Adrian",
        team: "The New Ravenfall Commanders",
        stats: {
          pass: 56,
          catch: 52,
          run: 54,
          block: 54,
          fight: 51,
          throw: 49,
          luck: 68,
          pronouns: "He/Them",
          civic_engagement: 54,
          alcohol_tolerance: 60,
          favorite_weapon: "Katar",
          pregame_ritual:
            "Eating a piece of honeycomb to 'sweeten' their victory.",
          literate: false,
        },
      },
      {
        name: "Rhett Gavrilla",
        team: "The New Ravenfall Commanders",
        stats: {
          pass: 68,
          catch: 64,
          run: 53,
          block: 56,
          fight: 68,
          throw: 59,
          luck: 59,
          pronouns: "They/Them",
          civic_engagement: 56,
          alcohol_tolerance: 59,
          favorite_weapon: "Woodsman's Axe",
          pregame_ritual:
            "Collecting a pebble from every field they've ever played on.",
          literate: true,
        },
      },
      {
        name: "Jessalin Zobias",
        team: "The New Ravenfall Commanders",
        stats: {
          pass: 57,
          catch: 54,
          run: 55,
          block: 42,
          fight: 52,
          throw: 53,
          luck: 56,
          pronouns: "He/Him",
          civic_engagement: 54,
          alcohol_tolerance: 53,
          favorite_weapon: "Military Fork",
          pregame_ritual: "Tugging on their left earlobe three times.",
          literate: true,
        },
      },
      {
        name: "Jozef Pepe",
        team: "The New Ravenfall Commanders",
        stats: {
          pass: 50,
          catch: 56,
          run: 60,
          block: 43,
          fight: 50,
          throw: 49,
          luck: 55,
          pronouns: "He/Him",
          civic_engagement: 64,
          alcohol_tolerance: 54,
          favorite_weapon: "Zweihander",
          pregame_ritual: "Seeing who on the team can belch the loudest.",
          literate: true,
        },
      },
      {
        name: "Croteau Osmo",
        team: "The New Ravenfall Commanders",
        stats: {
          pass: 68,
          catch: 51,
          run: 55,
          block: 50,
          fight: 62,
          throw: 52,
          luck: 54,
          pronouns: "She/Her",
          civic_engagement: 45,
          alcohol_tolerance: 66,
          favorite_weapon: "Broadsword",
          pregame_ritual: "Tying a red string around their pinky finger.",
          literate: true,
        },
      },
      {
        name: "Pirozzo Opal",
        team: "The New Ravenfall Commanders",
        stats: {
          pass: 47,
          catch: 58,
          run: 54,
          block: 51,
          fight: 51,
          throw: 53,
          luck: 57,
          pronouns: "He/Them",
          civic_engagement: 63,
          alcohol_tolerance: 55,
          favorite_weapon: "Kriegsmesser",
          pregame_ritual: "Sharing a piece of fermented fish with a teammate.",
          literate: true,
        },
      },
    ],
  },
  [TEAM_NAMES["The Oread's Summit Tamers"]]: {
    name: "The Oread's Summit Tamers",
    slug: "oreads-summit",
    losses: 0,
    wins: 0,
    score: 0,
    luck: 67,
    stadium: {
      name: "The High-Pass Pitch",
      location: "Oread's Summit",
      description:
        "A field built at a breathtaking altitude in a fortified mountain pass. The air is painfully thin, and the weather is dangerously unpredictable.",
      modifiers: ["Thin Air", "Sudden Blizzard", "Vertigo"],
    },
    healer: {
      name: "Carn Tibbetts",
      team: "The Oread's Summit Tamers",
      stats: {
        pass: 54,
        catch: 51,
        run: 59,
        block: 57,
        fight: 51,
        throw: 52,
        luck: 65,
        pronouns: "He/Him",
        civic_engagement: 59,
        alcohol_tolerance: 51,
        favorite_weapon: "Shortsword",
        pregame_ritual: "Tying a small, hand-carved wooden bird to their gear.",
        literate: true,
      },
    },
    players: [
      {
        name: "Odericus Juxon",
        team: "The Oread's Summit Tamers",
        stats: {
          pass: 51,
          catch: 62,
          run: 56,
          block: 50,
          fight: 45,
          throw: 60,
          luck: 55,
          pronouns: "She/Them",
          civic_engagement: 50,
          alcohol_tolerance: 58,
          favorite_weapon: "Talwar",
          pregame_ritual: "Slapping their own helmet until their ears ring.",
          literate: false,
        },
      },
      {
        name: "Kass Fogel",
        team: "The Oread's Summit Tamers",
        stats: {
          pass: 55,
          catch: 46,
          run: 59,
          block: 50,
          fight: 57,
          throw: 59,
          luck: 60,
          pronouns: "She/Them",
          civic_engagement: 57,
          alcohol_tolerance: 58,
          favorite_weapon: "Voulge",
          pregame_ritual:
            "Avoiding eye contact with anyone wearing the color green.",
          literate: true,
        },
      },
      {
        name: "Zadoc Wyatan",
        team: "The Oread's Summit Tamers",
        stats: {
          pass: 53,
          catch: 67,
          run: 60,
          block: 58,
          fight: 58,
          throw: 54,
          luck: 51,
          pronouns: "They/Them",
          civic_engagement: 60,
          alcohol_tolerance: 57,
          favorite_weapon: "Halberd",
          pregame_ritual:
            "Sharing a ceremonial, non-alcoholic grog from a communal cup.",
          literate: true,
        },
      },
      {
        name: "Alwyn Wandy",
        team: "The Oread's Summit Tamers",
        stats: {
          pass: 58,
          catch: 34,
          run: 56,
          block: 64,
          fight: 53,
          throw: 65,
          luck: 63,
          pronouns: "They/Them",
          civic_engagement: 53,
          alcohol_tolerance: 53,
          favorite_weapon: "Kriegsmesser",
          pregame_ritual:
            "Whispering a secret fear to the Trollball before the game.",
          literate: false,
        },
      },
      {
        name: "Dric Trilley",
        team: "The Oread's Summit Tamers",
        stats: {
          pass: 53,
          catch: 54,
          run: 59,
          block: 67,
          fight: 45,
          throw: 49,
          luck: 56,
          pronouns: "She/Them",
          civic_engagement: 48,
          alcohol_tolerance: 56,
          favorite_weapon: "Flail",
          pregame_ritual:
            "Reciting their grocery list backward to clear their mind.",
          literate: true,
        },
      },
      {
        name: "Swamy Ahasuerus",
        team: "The Oread's Summit Tamers",
        stats: {
          pass: 69,
          catch: 53,
          run: 50,
          block: 53,
          fight: 52,
          throw: 60,
          luck: 51,
          pronouns: "She/Them",
          civic_engagement: 50,
          alcohol_tolerance: 55,
          favorite_weapon: "Axe",
          pregame_ritual:
            "Dipping their hands in a bucket of ice-cold well water.",
          literate: false,
        },
      },
      {
        name: "Clippard Burr",
        team: "The Oread's Summit Tamers",
        stats: {
          pass: 38,
          catch: 60,
          run: 65,
          block: 57,
          fight: 57,
          throw: 62,
          luck: 60,
          pronouns: "She/Them",
          civic_engagement: 70,
          alcohol_tolerance: 49,
          favorite_weapon: "Lance",
          pregame_ritual:
            "Asking a teammate to tell them a story, but only the beginning.",
          literate: true,
        },
      },
      {
        name: "Mitran Mariand",
        team: "The Oread's Summit Tamers",
        stats: {
          pass: 58,
          catch: 54,
          run: 63,
          block: 42,
          fight: 57,
          throw: 51,
          luck: 44,
          pronouns: "He/Him",
          civic_engagement: 56,
          alcohol_tolerance: 60,
          favorite_weapon: "Dirk",
          pregame_ritual:
            "Exchanging well-wishes with their direct opponent before the game starts.",
          literate: true,
        },
      },
      {
        name: "Edme Virgil",
        team: "The Oread's Summit Tamers",
        stats: {
          pass: 60,
          catch: 45,
          run: 63,
          block: 56,
          fight: 62,
          throw: 62,
          luck: 59,
          pronouns: "They/Them",
          civic_engagement: 56,
          alcohol_tolerance: 53,
          favorite_weapon: "War Pick",
          pregame_ritual: "Singing a sea shanty completely out of tune.",
          literate: false,
        },
      },
      {
        name: "Saloma Talich",
        team: "The Oread's Summit Tamers",
        stats: {
          pass: 66,
          catch: 53,
          run: 48,
          block: 45,
          fight: 52,
          throw: 57,
          luck: 51,
          pronouns: "He/Him",
          civic_engagement: 57,
          alcohol_tolerance: 72,
          favorite_weapon: "Axe",
          pregame_ritual:
            "Getting a teammate to punch them in the shoulder, hard.",
          literate: true,
        },
      },
    ],
  },
  [TEAM_NAMES["The South Pole Yetis"]]: {
    name: "The South Pole Yetis",
    slug: "south-pole",
    losses: 0,
    wins: 0,
    score: 0,
    luck: 55,
    stadium: {
      name: "The South Pole Palisade",
      location: "A remote southern frontier town",
      description:
        "A crude, fortified playing field built from rough-hewn logs. It's less a stadium and more a stockade against the wilderness. The 'grass' is mostly frozen mud and straw.",
      modifiers: ["Freezing Rain", "Icy Field", "Wolf Pack Howling"],
    },
    healer: {
      name: "Seiter Aida",
      team: "The South Pole Yetis",
      stats: {
        pass: 50,
        catch: 50,
        run: 59,
        block: 46,
        fight: 48,
        throw: 67,
        luck: 52,
        pronouns: "They/Them",
        civic_engagement: 51,
        alcohol_tolerance: 57,
        favorite_weapon: "Club",
        pregame_ritual:
          "Smelling their own game-worn socks from the previous match.",
        literate: false,
      },
    },
    players: [
      {
        name: "Sale Tocci",
        team: "The South Pole Yetis",
        stats: {
          pass: 60,
          catch: 51,
          run: 54,
          block: 54,
          fight: 52,
          throw: 55,
          luck: 63,
          pronouns: "She/Her",
          civic_engagement: 69,
          alcohol_tolerance: 42,
          favorite_weapon: "Talwar",
          pregame_ritual: "Braiding their hair into tight, battle-ready rows.",
          literate: true,
        },
      },
      {
        name: "Ajit Serge",
        team: "The South Pole Yetis",
        stats: {
          pass: 50,
          catch: 54,
          run: 55,
          block: 51,
          fight: 59,
          throw: 58,
          luck: 62,
          pronouns: "He/Him",
          civic_engagement: 51,
          alcohol_tolerance: 57,
          favorite_weapon: "War Pick",
          pregame_ritual:
            "Listening to the wind for a sign of which way the game will turn.",
          literate: false,
        },
      },
      {
        name: "Isborne Krause",
        team: "The South Pole Yetis",
        stats: {
          pass: 50,
          catch: 55,
          run: 46,
          block: 61,
          fight: 51,
          throw: 47,
          luck: 56,
          pronouns: "He/Him",
          civic_engagement: 58,
          alcohol_tolerance: 58,
          favorite_weapon: "Flail",
          pregame_ritual:
            "Getting a teammate to punch them in the shoulder, hard.",
          literate: true,
        },
      },
      {
        name: "Selima Si",
        team: "The South Pole Yetis",
        stats: {
          pass: 58,
          catch: 61,
          run: 65,
          block: 60,
          fight: 53,
          throw: 49,
          luck: 55,
          pronouns: "She/Them",
          civic_engagement: 55,
          alcohol_tolerance: 53,
          favorite_weapon: "Broadsword",
          pregame_ritual:
            "Wearing a specific, garishly colored pair of undergarments.",
          literate: true,
        },
      },
      {
        name: "Duky Orelee",
        team: "The South Pole Yetis",
        stats: {
          pass: 55,
          catch: 41,
          run: 59,
          block: 67,
          fight: 48,
          throw: 56,
          luck: 52,
          pronouns: "He/Him",
          civic_engagement: 52,
          alcohol_tolerance: 61,
          favorite_weapon: "Kriegsmesser",
          pregame_ritual: "Clapping their hands a prime number of times.",
          literate: true,
        },
      },
      {
        name: "Sayers Erdda",
        team: "The South Pole Yetis",
        stats: {
          pass: 60,
          catch: 45,
          run: 49,
          block: 54,
          fight: 48,
          throw: 69,
          luck: 62,
          pronouns: "They/Them",
          civic_engagement: 56,
          alcohol_tolerance: 52,
          favorite_weapon: "Dagger",
          pregame_ritual: "Polishing their boots with bacon grease.",
          literate: false,
        },
      },
      {
        name: "Jessy Debbie",
        team: "The South Pole Yetis",
        stats: {
          pass: 61,
          catch: 53,
          run: 60,
          block: 48,
          fight: 59,
          throw: 54,
          luck: 44,
          pronouns: "They/Them",
          civic_engagement: 62,
          alcohol_tolerance: 49,
          favorite_weapon: "Great Axe",
          pregame_ritual: "Clapping their hands a prime number of times.",
          literate: true,
        },
      },
      {
        name: "Hilaire Guevara",
        team: "The South Pole Yetis",
        stats: {
          pass: 60,
          catch: 51,
          run: 47,
          block: 52,
          fight: 56,
          throw: 54,
          luck: 51,
          pronouns: "She/Her",
          civic_engagement: 53,
          alcohol_tolerance: 53,
          favorite_weapon: "Quarterstaff",
          pregame_ritual: "Reciting a short, epic poem about a past victory.",
          literate: false,
        },
      },
      {
        name: "Coussoule Bidle",
        team: "The South Pole Yetis",
        stats: {
          pass: 58,
          catch: 58,
          run: 63,
          block: 59,
          fight: 59,
          throw: 47,
          luck: 46,
          pronouns: "He/Him",
          civic_engagement: 59,
          alcohol_tolerance: 45,
          favorite_weapon: "Mallet",
          pregame_ritual:
            "Turning their helmet around three times before putting it on.",
          literate: true,
        },
      },
      {
        name: "Udela Dorkus",
        team: "The South Pole Yetis",
        stats: {
          pass: 54,
          catch: 60,
          run: 58,
          block: 54,
          fight: 53,
          throw: 59,
          luck: 51,
          pronouns: "She/Them",
          civic_engagement: 63,
          alcohol_tolerance: 47,
          favorite_weapon: "Quarterstaff",
          pregame_ritual: "Licking a whetstone.",
          literate: true,
        },
      },
    ],
  },
  [TEAM_NAMES["The Southport Narwhals"]]: {
    name: "The Southport Narwhals",
    slug: "southport",
    losses: 0,
    wins: 0,
    score: 0,
    luck: 48,
    stadium: {
      name: "The Cliffside Pitch",
      location: "Southport",
      description:
        "A perilous, windswept field built next to the town's lighthouse. There is no ocean-side barrier, and the wind is notoriously unpredictable. The tusk-like lighthouse is the only landmark.",
      modifiers: ["Gale-Force Winds", "Sea Spray", "Rocky Outcropping"],
    },
    healer: {
      name: "Sand Denys",
      team: "The Southport Narwhals",
      stats: {
        pass: 55,
        catch: 54,
        run: 50,
        block: 53,
        fight: 61,
        throw: 64,
        luck: 60,
        pronouns: "She/Her",
        civic_engagement: 68,
        alcohol_tolerance: 46,
        favorite_weapon: "Cestus",
        pregame_ritual:
          "Telling each other exaggerated lies about their own strength.",
        literate: false,
      },
    },
    players: [
      {
        name: "Blood Eppes",
        team: "The Southport Narwhals",
        stats: {
          pass: 56,
          catch: 54,
          run: 52,
          block: 47,
          fight: 64,
          throw: 63,
          luck: 54,
          pronouns: "He/Him",
          civic_engagement: 60,
          alcohol_tolerance: 56,
          favorite_weapon: "Cutlass",
          pregame_ritual:
            "Stretching their hamstrings for exactly seven minutes.",
          literate: false,
        },
      },
      {
        name: "Malcolm Goer",
        team: "The Southport Narwhals",
        stats: {
          pass: 56,
          catch: 36,
          run: 63,
          block: 65,
          fight: 56,
          throw: 58,
          luck: 59,
          pronouns: "They/Them",
          civic_engagement: 63,
          alcohol_tolerance: 55,
          favorite_weapon: "Morning Star",
          pregame_ritual: "Rubbing the Trollball on their armpits for 'grip'.",
          literate: true,
        },
      },
      {
        name: "Blanc Fantasia",
        team: "The Southport Narwhals",
        stats: {
          pass: 51,
          catch: 51,
          run: 60,
          block: 58,
          fight: 64,
          throw: 52,
          luck: 52,
          pronouns: "He/Them",
          civic_engagement: 43,
          alcohol_tolerance: 53,
          favorite_weapon: "Seax",
          pregame_ritual:
            "Arranging their gear in a perfect, aesthetically pleasing spiral.",
          literate: true,
        },
      },
      {
        name: "Loralyn Lyndy",
        team: "The Southport Narwhals",
        stats: {
          pass: 58,
          catch: 47,
          run: 58,
          block: 57,
          fight: 57,
          throw: 59,
          luck: 61,
          pronouns: "She/Them",
          civic_engagement: 49,
          alcohol_tolerance: 53,
          favorite_weapon: "Main-gauche",
          pregame_ritual:
            "Adjusting their codpiece with theatrical importance.",
          literate: true,
        },
      },
      {
        name: "Cibis Areta",
        team: "The Southport Narwhals",
        stats: {
          pass: 63,
          catch: 48,
          run: 57,
          block: 59,
          fight: 54,
          throw: 45,
          luck: 56,
          pronouns: "She/Them",
          civic_engagement: 61,
          alcohol_tolerance: 71,
          favorite_weapon: "Estoc",
          pregame_ritual:
            "Getting a teammate to pour a bucket of cold water over their head.",
          literate: true,
        },
      },
      {
        name: "Braden Gaile",
        team: "The Southport Narwhals",
        stats: {
          pass: 47,
          catch: 52,
          run: 53,
          block: 67,
          fight: 68,
          throw: 65,
          luck: 53,
          pronouns: "He/Them",
          civic_engagement: 57,
          alcohol_tolerance: 62,
          favorite_weapon: "Swordstaff",
          pregame_ritual:
            "Muttering a nonsensical rhyme to ward off bad spirits.",
          literate: true,
        },
      },
      {
        name: "Crescint Sonia",
        team: "The Southport Narwhals",
        stats: {
          pass: 65,
          catch: 64,
          run: 67,
          block: 47,
          fight: 44,
          throw: 53,
          luck: 59,
          pronouns: "He/Him",
          civic_engagement: 57,
          alcohol_tolerance: 54,
          favorite_weapon: "Warhammer",
          pregame_ritual: "Filing down a single fingernail into a sharp point.",
          literate: true,
        },
      },
      {
        name: "Cilurzo Sochor",
        team: "The Southport Narwhals",
        stats: {
          pass: 58,
          catch: 43,
          run: 54,
          block: 65,
          fight: 66,
          throw: 53,
          luck: 53,
          pronouns: "He/Him",
          civic_engagement: 60,
          alcohol_tolerance: 53,
          favorite_weapon: "Hatchet",
          pregame_ritual:
            "Giving the Trollball a heroic backstory before each game.",
          literate: true,
        },
      },
      {
        name: "Torey Dannye",
        team: "The Southport Narwhals",
        stats: {
          pass: 49,
          catch: 59,
          run: 55,
          block: 56,
          fight: 45,
          throw: 57,
          luck: 60,
          pronouns: "He/Him",
          civic_engagement: 51,
          alcohol_tolerance: 61,
          favorite_weapon: "Swordstaff",
          pregame_ritual:
            "Listening to the wind for a sign of which way the game will turn.",
          literate: true,
        },
      },
      {
        name: "Fineman Dolhenty",
        team: "The Southport Narwhals",
        stats: {
          pass: 51,
          catch: 49,
          run: 60,
          block: 55,
          fight: 54,
          throw: 48,
          luck: 48,
          pronouns: "She/Her",
          civic_engagement: 51,
          alcohol_tolerance: 55,
          favorite_weapon: "Kirkhammer",
          pregame_ritual: "Wearing a necklace of polished river stones.",
          literate: true,
        },
      },
    ],
  },
  [TEAM_NAMES["The Starlight Bazaar Bizarres"]]: {
    name: "The Starlight Bazaar Bizarres",
    slug: "starlight-bazaar",
    losses: 0,
    wins: 0,
    score: 0,
    luck: 63,
    stadium: {
      name: "The Grand Souk",
      location: "The Starlight Bazaar",
      description:
        "A temporary, fenced-off pitch in the absolute center of the chaotic Grand Bazaar. The game is constantly interrupted by merchants, stray animals, and thieves.",
      modifiers: ["Crowd Interference", "Exotic Animal Loose", "Pickpockets"],
    },
    healer: {
      name: "Essa Pattie",
      team: "The Starlight Bazaar Bizarres",
      stats: {
        pass: 57,
        catch: 55,
        run: 67,
        block: 56,
        fight: 52,
        throw: 45,
        luck: 53,
        pronouns: "He/Him",
        civic_engagement: 46,
        alcohol_tolerance: 54,
        favorite_weapon: "Horseman's Pick",
        pregame_ritual:
          "Sticking a specific type of feather in their helmet's plume.",
        literate: true,
      },
    },
    players: [
      {
        name: "Bush Heiner",
        team: "The Starlight Bazaar Bizarres",
        stats: {
          pass: 54,
          catch: 52,
          run: 66,
          block: 62,
          fight: 51,
          throw: 50,
          luck: 50,
          pronouns: "She/Her",
          civic_engagement: 50,
          alcohol_tolerance: 59,
          favorite_weapon: "Bastard Sword",
          pregame_ritual:
            "Jogging three laps around the perimeter of the field.",
          literate: true,
        },
      },
      {
        name: "Kristin Kronfeld",
        team: "The Starlight Bazaar Bizarres",
        stats: {
          pass: 58,
          catch: 56,
          run: 53,
          block: 55,
          fight: 41,
          throw: 59,
          luck: 45,
          pronouns: "She/Her",
          civic_engagement: 52,
          alcohol_tolerance: 60,
          favorite_weapon: "Broadsword",
          pregame_ritual:
            "Getting a teammate to punch them in the shoulder, hard.",
          literate: true,
        },
      },
      {
        name: "Milo Nelie",
        team: "The Starlight Bazaar Bizarres",
        stats: {
          pass: 61,
          catch: 66,
          run: 44,
          block: 45,
          fight: 49,
          throw: 53,
          luck: 52,
          pronouns: "He/Them",
          civic_engagement: 47,
          alcohol_tolerance: 61,
          favorite_weapon: "Military Fork",
          pregame_ritual:
            "Tracing an invisible, complex sigil over their heart.",
          literate: true,
        },
      },
      {
        name: "Pompei Hephzipa",
        team: "The Starlight Bazaar Bizarres",
        stats: {
          pass: 50,
          catch: 62,
          run: 48,
          block: 39,
          fight: 57,
          throw: 64,
          luck: 46,
          pronouns: "He/Him",
          civic_engagement: 56,
          alcohol_tolerance: 51,
          favorite_weapon: "Broadsword",
          pregame_ritual:
            "Performing a series of aggressive, theatrical poses.",
          literate: true,
        },
      },
      {
        name: "Melesa Zelten",
        team: "The Starlight Bazaar Bizarres",
        stats: {
          pass: 43,
          catch: 61,
          run: 59,
          block: 60,
          fight: 57,
          throw: 49,
          luck: 50,
          pronouns: "He/Him",
          civic_engagement: 56,
          alcohol_tolerance: 47,
          favorite_weapon: "Spear",
          pregame_ritual:
            "Leading the team in a synchronized chant that slowly gets louder.",
          literate: true,
        },
      },
      {
        name: "Demp Chet",
        team: "The Starlight Bazaar Bizarres",
        stats: {
          pass: 63,
          catch: 46,
          run: 52,
          block: 53,
          fight: 48,
          throw: 50,
          luck: 58,
          pronouns: "He/Him",
          civic_engagement: 53,
          alcohol_tolerance: 47,
          favorite_weapon: "Cutlass",
          pregame_ritual:
            "Staring at their reflection in a bucket of water until they feel 'ready'.",
          literate: false,
        },
      },
      {
        name: "Gagliano Tallbott",
        team: "The Starlight Bazaar Bizarres",
        stats: {
          pass: 57,
          catch: 48,
          run: 57,
          block: 53,
          fight: 64,
          throw: 61,
          luck: 56,
          pronouns: "He/Him",
          civic_engagement: 49,
          alcohol_tolerance: 64,
          favorite_weapon: "Broadsword",
          pregame_ritual:
            "Telling a terrible joke to the Trollball to 'loosen it up'.",
          literate: false,
        },
      },
      {
        name: "Aggri Cookie",
        team: "The Starlight Bazaar Bizarres",
        stats: {
          pass: 51,
          catch: 65,
          run: 54,
          block: 49,
          fight: 59,
          throw: 58,
          luck: 61,
          pronouns: "He/Him",
          civic_engagement: 58,
          alcohol_tolerance: 54,
          favorite_weapon: "Halberd",
          pregame_ritual:
            "Staring intently at their gauntlets, as if for the first time.",
          literate: true,
        },
      },
      {
        name: "Willa Lois",
        team: "The Starlight Bazaar Bizarres",
        stats: {
          pass: 45,
          catch: 41,
          run: 59,
          block: 63,
          fight: 43,
          throw: 43,
          luck: 51,
          pronouns: "They/Them",
          civic_engagement: 64,
          alcohol_tolerance: 52,
          favorite_weapon: "Dagger",
          pregame_ritual:
            "Plucking a single hair from a teammate's beard for luck.",
          literate: true,
        },
      },
      {
        name: "Quintessa Austine",
        team: "The Starlight Bazaar Bizarres",
        stats: {
          pass: 54,
          catch: 56,
          run: 46,
          block: 61,
          fight: 51,
          throw: 49,
          luck: 44,
          pronouns: "He/Him",
          civic_engagement: 53,
          alcohol_tolerance: 48,
          favorite_weapon: "Spiked Gauntlet",
          pregame_ritual:
            "Trying to start a 'slow clap' with the audience before the game has begun.",
          literate: true,
        },
      },
    ],
  },
  [TEAM_NAMES["The Tortell Privateers"]]: {
    name: "The Tortell Privateers",
    slug: "tortell",
    losses: 0,
    wins: 0,
    score: 0,
    luck: 48,
    stadium: {
      name: "The Junction Box",
      location: "Confluence",
      description:
        "A state-of-the-art stadium built at the precise point where the two great rivers of the megacity meet. Features retractable roofing and luxury boxes for the city's elite.",
      modifiers: ["Urban Distractions", "River Fog", "Hometown Crowd"],
    },
    healer: {
      name: "Eugen Zacks",
      team: "The Tortell Privateers",
      stats: {
        pass: 55,
        catch: 60,
        run: 55,
        block: 51,
        fight: 65,
        throw: 65,
        luck: 52,
        pronouns: "He/Him",
        civic_engagement: 64,
        alcohol_tolerance: 55,
        favorite_weapon: "Swordstaff",
        pregame_ritual: "Slapping their own helmet until their ears ring.",
        literate: true,
      },
    },
    players: [
      {
        name: "Lilithe Royce",
        team: "The Tortell Privateers",
        stats: {
          pass: 52,
          catch: 59,
          run: 59,
          block: 51,
          fight: 49,
          throw: 57,
          luck: 52,
          pronouns: "She/Them",
          civic_engagement: 57,
          alcohol_tolerance: 51,
          favorite_weapon: "Mace",
          pregame_ritual:
            "Sticking leeches to their legs to 'lighten their step'.",
          literate: false,
        },
      },
      {
        name: "Castorina Gies",
        team: "The Tortell Privateers",
        stats: {
          pass: 48,
          catch: 65,
          run: 66,
          block: 52,
          fight: 59,
          throw: 51,
          luck: 56,
          pronouns: "He/Him",
          civic_engagement: 56,
          alcohol_tolerance: 55,
          favorite_weapon: "Sickle",
          pregame_ritual:
            "Bribing a local oracle with a meat pie for a vague prophecy.",
          literate: true,
        },
      },
      {
        name: "Melisande Eustacia",
        team: "The Tortell Privateers",
        stats: {
          pass: 70,
          catch: 59,
          run: 53,
          block: 61,
          fight: 61,
          throw: 39,
          luck: 52,
          pronouns: "He/Him",
          civic_engagement: 44,
          alcohol_tolerance: 64,
          favorite_weapon: "Talwar",
          pregame_ritual: "Reviewing hand signals for secret plays.",
          literate: false,
        },
      },
      {
        name: "Loralee Sunny",
        team: "The Tortell Privateers",
        stats: {
          pass: 46,
          catch: 54,
          run: 60,
          block: 59,
          fight: 53,
          throw: 55,
          luck: 66,
          pronouns: "She/Them",
          civic_engagement: 47,
          alcohol_tolerance: 63,
          favorite_weapon: "War Scythe",
          pregame_ritual:
            "Reading their own fortune in a scattering of knuckle bones.",
          literate: true,
        },
      },
      {
        name: "Kidder Starkey",
        team: "The Tortell Privateers",
        stats: {
          pass: 50,
          catch: 59,
          run: 65,
          block: 64,
          fight: 57,
          throw: 58,
          luck: 53,
          pronouns: "He/Them",
          civic_engagement: 52,
          alcohol_tolerance: 54,
          favorite_weapon: "Rapier",
          pregame_ritual:
            "Thanking their armor for the protection it's about to offer.",
          literate: false,
        },
      },
      {
        name: "Keisling Damalas",
        team: "The Tortell Privateers",
        stats: {
          pass: 56,
          catch: 55,
          run: 53,
          block: 63,
          fight: 64,
          throw: 63,
          luck: 46,
          pronouns: "He/Them",
          civic_engagement: 65,
          alcohol_tolerance: 57,
          favorite_weapon: "Rondel Dagger",
          pregame_ritual:
            "Painting their teeth with a mixture of charcoal and water.",
          literate: false,
        },
      },
      {
        name: "Goldberg Tova",
        team: "The Tortell Privateers",
        stats: {
          pass: 50,
          catch: 58,
          run: 62,
          block: 65,
          fight: 66,
          throw: 54,
          luck: 65,
          pronouns: "She/Them",
          civic_engagement: 60,
          alcohol_tolerance: 52,
          favorite_weapon: "Glaive",
          pregame_ritual:
            "Doing a series of loud, guttural breathing exercises.",
          literate: false,
        },
      },
      {
        name: "Ellan Elburt",
        team: "The Tortell Privateers",
        stats: {
          pass: 51,
          catch: 57,
          run: 54,
          block: 50,
          fight: 64,
          throw: 59,
          luck: 44,
          pronouns: "He/Them",
          civic_engagement: 48,
          alcohol_tolerance: 44,
          favorite_weapon: "Tabar",
          pregame_ritual:
            "Reciting their grocery list backward to clear their mind.",
          literate: true,
        },
      },
      {
        name: "Payson Jan",
        team: "The Tortell Privateers",
        stats: {
          pass: 54,
          catch: 52,
          run: 60,
          block: 56,
          fight: 59,
          throw: 63,
          luck: 55,
          pronouns: "He/Him",
          civic_engagement: 63,
          alcohol_tolerance: 46,
          favorite_weapon: "Tabar",
          pregame_ritual: "Clapping their hands a prime number of times.",
          literate: true,
        },
      },
      {
        name: "Dib Tufts",
        team: "The Tortell Privateers",
        stats: {
          pass: 63,
          catch: 60,
          run: 57,
          block: 59,
          fight: 58,
          throw: 62,
          luck: 58,
          pronouns: "He/Them",
          civic_engagement: 49,
          alcohol_tolerance: 48,
          favorite_weapon: "Axe",
          pregame_ritual: "Chugging a raw egg, shell and all.",
          literate: true,
        },
      },
    ],
  },
  [TEAM_NAMES["The Wyrmwood Stronghammers"]]: {
    name: "The Wyrmwood Stronghammers",
    slug: "wyrmwood",
    losses: 0,
    wins: 0,
    score: 0,
    luck: 66,
    stadium: {
      name: "The Sawpit",
      location: "Wyrmwood",
      description:
        "A huge clearing in the ancient forest, surrounded by giant, felled trees that serve as crude bleachers. The 'field' is a mix of sawdust, mud, and tangled roots.",
      modifiers: ["Tangled Roots", "Sawdust Cloud", "'Timber!'"],
    },
    healer: {
      name: "Hamburger Marthe",
      team: "The Wyrmwood Stronghammers",
      stats: {
        pass: 51,
        catch: 54,
        run: 46,
        block: 67,
        fight: 61,
        throw: 54,
        luck: 54,
        pronouns: "He/Him",
        civic_engagement: 59,
        alcohol_tolerance: 61,
        favorite_weapon: "Arming Sword",
        pregame_ritual:
          "Seeing how many dried beans they can fit in their nostril.",
        literate: true,
      },
    },
    players: [
      {
        name: "Sabian Gleason",
        team: "The Wyrmwood Stronghammers",
        stats: {
          pass: 51,
          catch: 54,
          run: 48,
          block: 42,
          fight: 67,
          throw: 52,
          luck: 57,
          pronouns: "He/Him",
          civic_engagement: 44,
          alcohol_tolerance: 55,
          favorite_weapon: "Maul",
          pregame_ritual: "Counting the number of clouds in the sky.",
          literate: false,
        },
      },
      {
        name: "Ultun Barthelemy",
        team: "The Wyrmwood Stronghammers",
        stats: {
          pass: 55,
          catch: 58,
          run: 58,
          block: 54,
          fight: 59,
          throw: 58,
          luck: 59,
          pronouns: "He/Him",
          civic_engagement: 52,
          alcohol_tolerance: 48,
          favorite_weapon: "Partisan",
          pregame_ritual: "Braiding a teammate's nose hair.",
          literate: false,
        },
      },
      {
        name: "Autumn Jodoin",
        team: "The Wyrmwood Stronghammers",
        stats: {
          pass: 53,
          catch: 43,
          run: 59,
          block: 54,
          fight: 48,
          throw: 63,
          luck: 55,
          pronouns: "He/Him",
          civic_engagement: 61,
          alcohol_tolerance: 46,
          favorite_weapon: "Trident",
          pregame_ritual: "Chugging a raw egg, shell and all.",
          literate: true,
        },
      },
      {
        name: "Kerwin Gasper",
        team: "The Wyrmwood Stronghammers",
        stats: {
          pass: 60,
          catch: 48,
          run: 51,
          block: 55,
          fight: 58,
          throw: 63,
          luck: 54,
          pronouns: "They/Them",
          civic_engagement: 65,
          alcohol_tolerance: 56,
          favorite_weapon: "Kriegsmesser",
          pregame_ritual: "Asking the referee to bless their weapon.",
          literate: true,
        },
      },
      {
        name: "Calvinna Isador",
        team: "The Wyrmwood Stronghammers",
        stats: {
          pass: 57,
          catch: 47,
          run: 44,
          block: 41,
          fight: 57,
          throw: 51,
          luck: 66,
          pronouns: "She/Them",
          civic_engagement: 55,
          alcohol_tolerance: 51,
          favorite_weapon: "Dagger",
          pregame_ritual:
            "Giving a rambling, often nonsensical 'pump-up' speech.",
          literate: false,
        },
      },
      {
        name: "Cornela Piscatelli",
        team: "The Wyrmwood Stronghammers",
        stats: {
          pass: 55,
          catch: 62,
          run: 59,
          block: 58,
          fight: 56,
          throw: 66,
          luck: 60,
          pronouns: "He/Him",
          civic_engagement: 48,
          alcohol_tolerance: 68,
          pregame_ritual: "Braiding a teammate's nose hair.",
          literate: false,
        },
      },
      {
        name: "Rebane Kendy",
        team: "The Wyrmwood Stronghammers",
        stats: {
          pass: 61,
          catch: 51,
          run: 53,
          block: 56,
          fight: 45,
          throw: 60,
          luck: 43,
          pronouns: "He/Them",
          civic_engagement: 60,
          alcohol_tolerance: 59,
          favorite_weapon: "Bastard Sword",
          pregame_ritual: "Tugging on their left earlobe three times.",
          literate: true,
        },
      },
      {
        name: "Sondra Elaina",
        team: "The Wyrmwood Stronghammers",
        stats: {
          pass: 55,
          catch: 54,
          run: 56,
          block: 59,
          fight: 49,
          throw: 59,
          luck: 53,
          pronouns: "She/Her",
          civic_engagement: 64,
          alcohol_tolerance: 52,
          favorite_weapon: "Cudgel",
          pregame_ritual: "Polishing their boots with bacon grease.",
          literate: false,
        },
      },
      {
        name: "Odelia Abbott",
        team: "The Wyrmwood Stronghammers",
        stats: {
          pass: 66,
          catch: 48,
          run: 54,
          block: 58,
          fight: 56,
          throw: 55,
          luck: 58,
          pronouns: "He/Him",
          civic_engagement: 53,
          alcohol_tolerance: 44,
          favorite_weapon: "Whip",
          pregame_ritual:
            "Finding the muddiest puddle and stomping in it with bare feet.",
          literate: true,
        },
      },
      {
        name: "Godart Urissa",
        team: "The Wyrmwood Stronghammers",
        stats: {
          pass: 49,
          catch: 56,
          run: 58,
          block: 52,
          fight: 43,
          throw: 70,
          luck: 52,
          pronouns: "They/Them",
          civic_engagement: 59,
          alcohol_tolerance: 44,
          favorite_weapon: "Cestus",
          pregame_ritual:
            "Insisting on wearing a ridiculously oversized, floppy hat during warm-ups.",
          literate: true,
        },
      },
    ],
  },
  [TEAM_NAMES["The Zmeigorod Snessengers"]]: {
    name: "The Zmeigorod Snessengers",
    slug: "zmeigorod",
    losses: 0,
    wins: 0,
    score: 0,
    luck: 53,
    stadium: {
      name: "The Serpent's Pass",
      location: "Zmeigorod, just west of the lumber mill",
      modifiers: ["Altitude Sickness", "Sudden Downpour", "Rockslide"],
      description:
        "Has to be periodically rebuilt whenever the old stadium starts sinking into the swamp. Don’t worry about it",
    },
    healer: {
      name: "Waldon Tadeo",
      team: "The Zmeigorod Snessengers",
      stats: {
        pass: 56,
        catch: 65,
        run: 55,
        block: 56,
        fight: 54,
        throw: 60,
        luck: 50,
        pronouns: "She/Them",
        civic_engagement: 56,
        alcohol_tolerance: 53,
        favorite_weapon: "Battle Axe",
        pregame_ritual:
          "Rubbing a foul-smelling local mushroom on their elbows for flexibility.",
        literate: false,
      },
    },
    players: [
      {
        name: "Delija Dowling",
        team: "The Zmeigorod Snessengers",
        stats: {
          pass: 47,
          catch: 55,
          run: 50,
          block: 51,
          fight: 53,
          throw: 56,
          luck: 58,
          pronouns: "He/Him",
          civic_engagement: 60,
          alcohol_tolerance: 61,
          favorite_weapon: "Seax",
          pregame_ritual: "Chugging a raw egg, shell and all.",
          literate: true,
        },
      },
      {
        name: "Northway Orran",
        team: "The Zmeigorod Snessengers",
        stats: {
          pass: 54,
          catch: 49,
          run: 60,
          block: 55,
          fight: 66,
          throw: 53,
          luck: 53,
          pronouns: "She/Them",
          civic_engagement: 58,
          alcohol_tolerance: 59,
          favorite_weapon: "Machete",
          pregame_ritual:
            "Performing a series of aggressive, theatrical poses.",
          literate: false,
        },
      },
      {
        name: "Evalyn Pierrepont",
        team: "The Zmeigorod Snessengers",
        stats: {
          pass: 57,
          catch: 49,
          run: 66,
          block: 54,
          fight: 48,
          throw: 50,
          luck: 53,
          pronouns: "He/Him",
          civic_engagement: 53,
          alcohol_tolerance: 66,
          favorite_weapon: "Seax",
          pregame_ritual:
            "Polishing their helmet with a live snail for good luck.",
          literate: false,
        },
      },
      {
        name: "Rose Kluge",
        team: "The Zmeigorod Snessengers",
        stats: {
          pass: 51,
          catch: 54,
          run: 63,
          block: 49,
          fight: 52,
          throw: 52,
          luck: 55,
          pronouns: "She/Her",
          civic_engagement: 53,
          alcohol_tolerance: 46,
          favorite_weapon: "Cudgel",
          pregame_ritual:
            "Tensing every muscle in their body at once, then releasing.",
          literate: false,
        },
      },
      {
        name: "Gere Cordelie",
        team: "The Zmeigorod Snessengers",
        stats: {
          pass: 55,
          catch: 47,
          run: 42,
          block: 68,
          fight: 53,
          throw: 48,
          luck: 46,
          pronouns: "She/Her",
          civic_engagement: 50,
          alcohol_tolerance: 47,
          pregame_ritual:
            "Performing a series of aggressive, theatrical poses.",
          literate: true,
        },
      },
      {
        name: "Kleinstein MacGregor",
        team: "The Zmeigorod Snessengers",
        stats: {
          pass: 43,
          catch: 59,
          run: 61,
          block: 53,
          fight: 52,
          throw: 59,
          luck: 68,
          pronouns: "She/Her",
          civic_engagement: 52,
          alcohol_tolerance: 63,
          favorite_weapon: "Machete",
          pregame_ritual: "Clapping their hands a prime number of times.",
          literate: false,
        },
      },
      {
        name: "Avaria Revell",
        team: "The Zmeigorod Snessengers",
        stats: {
          pass: 53,
          catch: 46,
          run: 67,
          block: 50,
          fight: 54,
          throw: 57,
          luck: 61,
          pronouns: "She/Her",
          civic_engagement: 59,
          alcohol_tolerance: 66,
          favorite_weapon: "Bastard Sword",
          pregame_ritual:
            "Sharing a ceremonial, non-alcoholic grog from a communal cup.",
          literate: true,
        },
      },
      {
        name: "Alded Sanjay",
        team: "The Zmeigorod Snessengers",
        stats: {
          pass: 45,
          catch: 61,
          run: 56,
          block: 54,
          fight: 51,
          throw: 61,
          luck: 57,
          pronouns: "He/Him",
          civic_engagement: 58,
          alcohol_tolerance: 51,
          favorite_weapon: "War Scythe",
          pregame_ritual:
            "Looking each teammate in the eye and giving a single, firm nod.",
          literate: false,
        },
      },
      {
        name: "Arni Griffith",
        team: "The Zmeigorod Snessengers",
        stats: {
          pass: 47,
          catch: 62,
          run: 43,
          block: 56,
          fight: 51,
          throw: 55,
          luck: 53,
          pronouns: "He/Them",
          civic_engagement: 47,
          alcohol_tolerance: 49,
          favorite_weapon: "Woodsman's Axe",
          pregame_ritual:
            "Giving the Trollball a heroic backstory before each game.",
          literate: true,
        },
      },
      {
        name: "Dare Wynnie",
        team: "The Zmeigorod Snessengers",
        stats: {
          pass: 64,
          catch: 54,
          run: 50,
          block: 54,
          fight: 62,
          throw: 52,
          luck: 59,
          pronouns: "She/Them",
          civic_engagement: 60,
          alcohol_tolerance: 45,
          favorite_weapon: "Quarterstaff",
          pregame_ritual:
            "Painting a single, matching stripe of mud on each player's face.",
          literate: false,
        },
      },
    ],
  },
};
