import { team, TEAM_NAMES } from "./types";

export const TEAMS: Record<TEAM_NAMES, team> = {
  [TEAM_NAMES["The Brimstone Slayers"]]: {
    name: TEAM_NAMES["The Brimstone Slayers"],
    slug: "brimstone",
    losses: 0,
    wins: 0,
    score: 0,
    luck: 53,
    sponsor: "The Sanguine Order",
    stadium: {
      name: "The Su'akour Bowl",
      location: "Brimstone (Su'akour Ruins)",
      description:
        "A crude, rowdy stadium built within the half-finished, black-stone walls of the warlord Su'akour's abandoned fortress, now sponsored by the Sanguine Order. The stands are crumbling ruins, and the entire arena perpetually stinks of the nearby sulfur marshes.",
      modifiers: ["Noxious Fumes", "Crumbling Walls", "Uneven Ground"],
    },
    healer: {
      name: "Raphael Miyasawa",
      team: TEAM_NAMES["The Brimstone Slayers"],
      stats: {
        pass: 46,
        catch: 49,
        run: 63,
        block: 56,
        fight: 60,
        throw: 60,
        luck: 63,
        pronouns: "She/Them",
        civic_engagement: 58,
        alcohol_tolerance: 56,
        favorite_weapon: "Cestus",
        pregame_ritual:
          "Kissing their biceps and whispering words of encouragement to them.",
        literate: true,
      },
    },
    players: [
      {
        name: "Bollinger Susette",
        team: TEAM_NAMES["The Brimstone Slayers"],
        stats: {
          pass: 59,
          catch: 52,
          run: 46,
          block: 47,
          fight: 42,
          throw: 53,
          luck: 50,
          pronouns: "He/Him",
          civic_engagement: 56,
          alcohol_tolerance: 60,
          favorite_weapon: "Hatchet",
          pregame_ritual:
            "Getting a teammate to punch them in the shoulder, hard.",
          literate: true,
        },
      },
      {
        name: "Nachison Icken",
        team: TEAM_NAMES["The Brimstone Slayers"],
        stats: {
          pass: 61,
          catch: 55,
          run: 43,
          block: 52,
          fight: 50,
          throw: 46,
          luck: 47,
          pronouns: "She/Them",
          civic_engagement: 42,
          alcohol_tolerance: 57,
          favorite_weapon: "Claymore",
          pregame_ritual:
            "Wearing their boots on the wrong feet during the warm-up.",
          literate: true,
        },
      },
      {
        name: "Glassman Solley",
        team: TEAM_NAMES["The Brimstone Slayers"],
        stats: {
          pass: 54,
          catch: 50,
          run: 69,
          block: 62,
          fight: 58,
          throw: 42,
          luck: 53,
          pronouns: "He/Them",
          civic_engagement: 53,
          alcohol_tolerance: 55,
          favorite_weapon: "Rondel Dagger",
          pregame_ritual: "Washing their hands with dirt.",
          literate: false,
        },
      },
      {
        name: "Wylde Jutta",
        team: TEAM_NAMES["The Brimstone Slayers"],
        stats: {
          pass: 63,
          catch: 61,
          run: 61,
          block: 49,
          fight: 67,
          throw: 51,
          luck: 52,
          pronouns: "She/Them",
          civic_engagement: 66,
          alcohol_tolerance: 52,
          favorite_weapon: "Voulge",
          pregame_ritual:
            "Asking a teammate to tell them a story, but only the beginning.",
          literate: true,
        },
      },
      {
        name: "Selimah Tully",
        team: TEAM_NAMES["The Brimstone Slayers"],
        stats: {
          pass: 57,
          catch: 54,
          run: 57,
          block: 60,
          fight: 52,
          throw: 53,
          luck: 48,
          pronouns: "He/Him",
          civic_engagement: 61,
          alcohol_tolerance: 58,
          favorite_weapon: "Dagger",
          pregame_ritual: "Asking the referee to bless their weapon.",
          literate: false,
        },
      },
      {
        name: "Campball Fink",
        team: TEAM_NAMES["The Brimstone Slayers"],
        stats: {
          pass: 56,
          catch: 60,
          run: 51,
          block: 61,
          fight: 66,
          throw: 43,
          luck: 61,
          pronouns: "She/Them",
          civic_engagement: 57,
          alcohol_tolerance: 55,
          favorite_weapon: "Swordstaff",
          pregame_ritual:
            "Finding the muddiest puddle and stomping in it with bare feet.",
          literate: false,
        },
      },
      {
        name: "Lowson Hersh",
        team: TEAM_NAMES["The Brimstone Slayers"],
        stats: {
          pass: 58,
          catch: 43,
          run: 49,
          block: 44,
          fight: 48,
          throw: 60,
          luck: 58,
          pronouns: "They/Them",
          civic_engagement: 59,
          alcohol_tolerance: 63,
          favorite_weapon: "Spiked Gauntlet",
          pregame_ritual:
            "Staring at a single blade of grass until their eyes water.",
          literate: false,
        },
      },
      {
        name: "Oona Jane",
        team: TEAM_NAMES["The Brimstone Slayers"],
        stats: {
          pass: 42,
          catch: 55,
          run: 58,
          block: 46,
          fight: 51,
          throw: 55,
          luck: 46,
          pronouns: "She/Her",
          civic_engagement: 57,
          alcohol_tolerance: 53,
          favorite_weapon: "Cudgel",
          pregame_ritual: "Wiping a teammate's sweat onto their own forehead.",
          literate: true,
        },
      },
      {
        name: "Orlina Jerrine",
        team: TEAM_NAMES["The Brimstone Slayers"],
        stats: {
          pass: 61,
          catch: 57,
          run: 57,
          block: 50,
          fight: 54,
          throw: 52,
          luck: 49,
          pronouns: "He/Him",
          civic_engagement: 50,
          alcohol_tolerance: 45,
          favorite_weapon: "Rapier",
          pregame_ritual: "Attempting to communicate with birds.",
          literate: true,
        },
      },
      {
        name: "Nigel Rothmuller",
        team: TEAM_NAMES["The Brimstone Slayers"],
        stats: {
          pass: 58,
          catch: 60,
          run: 56,
          block: 52,
          fight: 43,
          throw: 59,
          luck: 62,
          pronouns: "They/Them",
          civic_engagement: 52,
          alcohol_tolerance: 57,
          favorite_weapon: "Spear",
          pregame_ritual:
            "Consulting a folk rhyme about the weather to predict the game's outcome.",
          literate: true,
        },
      },
    ],
  },
  [TEAM_NAMES["The Confluence Captains"]]: {
    name: TEAM_NAMES["The Confluence Captains"],
    slug: "confluence",
    losses: 0,
    wins: 0,
    score: 0,
    luck: 60,
    sponsor: "The Guild of the Black Sky",
    stadium: {
      name: "The Glowstone Terrace",
      location: "Confluence (World's Spine Mountains)",
      description:
        "A massive, opulent stadium built on one of the city's main terraces, carved directly into the mountainside. The field is famously paved with polished Glowstone, and the stands overlook the bustling Confluence Market and the ongoing construction of the Guild's Skyport.",
      modifiers: ["Glowstone Glare", "Mountain Wind", "Market Day Crowd"],
    },
    healer: {
      name: "Kant Langill",
      team: TEAM_NAMES["The Confluence Captains"],
      stats: {
        pass: 51,
        catch: 55,
        run: 54,
        block: 49,
        fight: 59,
        throw: 59,
        luck: 65,
        pronouns: "He/Him",
        civic_engagement: 68,
        alcohol_tolerance: 65,
        favorite_weapon: "Scimitar",
        pregame_ritual:
          "Doing a terrible, clumsy dance to 'loosen the joints'.",
        literate: true,
      },
    },
    players: [
      {
        name: "Ladew Evelina",
        team: TEAM_NAMES["The Confluence Captains"],
        stats: {
          pass: 56,
          catch: 65,
          run: 58,
          block: 63,
          fight: 65,
          throw: 64,
          luck: 71,
          pronouns: "She/Them",
          civic_engagement: 46,
          alcohol_tolerance: 56,
          favorite_weapon: "Axe",
          pregame_ritual: "Chugging a raw egg, shell and all.",
          literate: true,
        },
      },
      {
        name: "Deach Sharlene",
        team: TEAM_NAMES["The Confluence Captains"],
        stats: {
          pass: 56,
          catch: 55,
          run: 52,
          block: 52,
          fight: 52,
          throw: 56,
          luck: 62,
          pronouns: "He/Them",
          civic_engagement: 52,
          alcohol_tolerance: 60,
          favorite_weapon: "Rapier",
          pregame_ritual:
            "Wearing their boots on the wrong feet during the warm-up.",
          literate: false,
        },
      },
      {
        name: "Stephan Lisk",
        team: TEAM_NAMES["The Confluence Captains"],
        stats: {
          pass: 60,
          catch: 57,
          run: 55,
          block: 59,
          fight: 60,
          throw: 56,
          luck: 51,
          pronouns: "He/Him",
          civic_engagement: 57,
          alcohol_tolerance: 58,
          favorite_weapon: "Pollaxe",
          pregame_ritual:
            "Arm-wrestling the player who plays the same position on their team.",
          literate: true,
        },
      },
      {
        name: "O'Conner Maighdlin",
        team: TEAM_NAMES["The Confluence Captains"],
        stats: {
          pass: 56,
          catch: 66,
          run: 66,
          block: 60,
          fight: 62,
          throw: 54,
          luck: 59,
          pronouns: "He/Him",
          civic_engagement: 62,
          alcohol_tolerance: 57,
          favorite_weapon: "Hatchet",
          pregame_ritual:
            "Speaking only in rhymes for the hour before the game.",
          literate: true,
        },
      },
      {
        name: "Belding Chloe",
        team: TEAM_NAMES["The Confluence Captains"],
        stats: {
          pass: 53,
          catch: 65,
          run: 62,
          block: 72,
          fight: 58,
          throw: 61,
          luck: 42,
          pronouns: "She/Her",
          civic_engagement: 57,
          alcohol_tolerance: 47,
          favorite_weapon: "Lance",
          pregame_ritual: "Rubbing the Trollball on their armpits for 'grip'.",
          literate: true,
        },
      },
      {
        name: "Behl Berstine",
        team: TEAM_NAMES["The Confluence Captains"],
        stats: {
          pass: 61,
          catch: 58,
          run: 65,
          block: 59,
          fight: 42,
          throw: 58,
          luck: 52,
          pronouns: "They/Them",
          civic_engagement: 53,
          alcohol_tolerance: 49,
          favorite_weapon: "Axe",
          pregame_ritual:
            "Wearing their boots on the wrong feet during the warm-up.",
          literate: false,
        },
      },
      {
        name: "Caves Cestar",
        team: TEAM_NAMES["The Confluence Captains"],
        stats: {
          pass: 54,
          catch: 52,
          run: 63,
          block: 50,
          fight: 60,
          throw: 55,
          luck: 66,
          pronouns: "He/Him",
          civic_engagement: 57,
          alcohol_tolerance: 54,
          favorite_weapon: "Maul",
          pregame_ritual:
            "Going over the game plan drawn in the dirt with the team captain.",
          literate: false,
        },
      },
      {
        name: "Vonni Geoff",
        team: TEAM_NAMES["The Confluence Captains"],
        stats: {
          pass: 60,
          catch: 62,
          run: 57,
          block: 51,
          fight: 49,
          throw: 49,
          luck: 58,
          pronouns: "He/Him",
          civic_engagement: 67,
          alcohol_tolerance: 65,
          favorite_weapon: "Sap",
          pregame_ritual:
            "Covering their forearms in a sticky tree sap for 'grip'.",
          literate: false,
        },
      },
      {
        name: "Carnahan Laud",
        team: TEAM_NAMES["The Confluence Captains"],
        stats: {
          pass: 46,
          catch: 63,
          run: 73,
          block: 49,
          fight: 59,
          throw: 53,
          luck: 60,
          pronouns: "She/Her",
          civic_engagement: 62,
          alcohol_tolerance: 68,
          favorite_weapon: "Lance",
          pregame_ritual: "Eating a dandelion, stem and all.",
          literate: false,
        },
      },
      {
        name: "Richia Pazit",
        team: TEAM_NAMES["The Confluence Captains"],
        stats: {
          pass: 61,
          catch: 42,
          run: 57,
          block: 55,
          fight: 45,
          throw: 50,
          luck: 59,
          pronouns: "They/Them",
          civic_engagement: 55,
          alcohol_tolerance: 55,
          favorite_weapon: "Pike",
          pregame_ritual: "Headbutting their own team's goal post (gently).",
          literate: true,
        },
      },
    ],
  },
  [TEAM_NAMES["The Desert Spectres"]]: {
    name: TEAM_NAMES["The Desert Spectres"],
    slug: "desert",
    losses: 0,
    wins: 0,
    score: 0,
    luck: 61,
    sponsor: "Geth, the Gravelord",
    stadium: {
      name: "The Sun-Baked Bowl",
      location: "The Great Desert",
      description:
        "A simple, deep bowl dug from clay and sandstone on the edge of a caravan oasis. The heat is oppressive, and the 'stands' are just blankets laid on the sun-baked dunes.",
      modifiers: ["Intense Heat", "Sandstorm", "Dehydration"],
    },
    healer: {
      name: "Verlee Dacia",
      team: TEAM_NAMES["The Desert Spectres"],
      stats: {
        pass: 54,
        catch: 53,
        run: 68,
        block: 50,
        fight: 40,
        throw: 47,
        luck: 57,
        pronouns: "She/Her",
        civic_engagement: 60,
        alcohol_tolerance: 66,
        favorite_weapon: "Billhook",
        pregame_ritual:
          "Eating a piece of honeycomb to 'sweeten' their victory.",
        literate: true,
      },
    },
    players: [
      {
        name: "Fidellia Mozelle",
        team: TEAM_NAMES["The Desert Spectres"],
        stats: {
          pass: 40,
          catch: 57,
          run: 60,
          block: 56,
          fight: 65,
          throw: 67,
          luck: 57,
          pronouns: "She/Them",
          civic_engagement: 56,
          alcohol_tolerance: 60,
          favorite_weapon: "Swordstaff",
          pregame_ritual: "Smelling a piece of burnt wood from a campfire.",
          literate: false,
        },
      },
      {
        name: "Muscolo Jaehne",
        team: TEAM_NAMES["The Desert Spectres"],
        stats: {
          pass: 58,
          catch: 50,
          run: 53,
          block: 39,
          fight: 60,
          throw: 53,
          luck: 49,
          pronouns: "They/Them",
          civic_engagement: 46,
          alcohol_tolerance: 54,
          favorite_weapon: "Seax",
          pregame_ritual:
            "Methodically tearing a large leaf into tiny, identical pieces.",
          literate: false,
        },
      },
      {
        name: "Eileen Mikihisa",
        team: TEAM_NAMES["The Desert Spectres"],
        stats: {
          pass: 45,
          catch: 54,
          run: 59,
          block: 60,
          fight: 55,
          throw: 55,
          luck: 57,
          pronouns: "He/Him",
          civic_engagement: 51,
          alcohol_tolerance: 51,
          favorite_weapon: "Longsword",
          pregame_ritual:
            "Trying to teach a stray dog a complicated and useless new trick.",
          literate: false,
        },
      },
      {
        name: "Bahr Ethelstan",
        team: TEAM_NAMES["The Desert Spectres"],
        stats: {
          pass: 62,
          catch: 61,
          run: 62,
          block: 49,
          fight: 60,
          throw: 52,
          luck: 53,
          pronouns: "They/Them",
          civic_engagement: 59,
          alcohol_tolerance: 53,
          favorite_weapon: "Blackjack",
          pregame_ritual: "Humming a tune they believe only they know.",
          literate: false,
        },
      },
      {
        name: "Heyes Iver",
        team: TEAM_NAMES["The Desert Spectres"],
        stats: {
          pass: 55,
          catch: 60,
          run: 61,
          block: 51,
          fight: 54,
          throw: 71,
          luck: 49,
          pronouns: "He/Him",
          civic_engagement: 67,
          alcohol_tolerance: 48,
          favorite_weapon: "Woodsman's Axe",
          pregame_ritual: "Tugging on their left earlobe three times.",
          literate: false,
        },
      },
      {
        name: "Angelita Darce",
        team: TEAM_NAMES["The Desert Spectres"],
        stats: {
          pass: 52,
          catch: 50,
          run: 58,
          block: 53,
          fight: 56,
          throw: 58,
          luck: 58,
          pronouns: "He/Him",
          civic_engagement: 62,
          alcohol_tolerance: 65,
          favorite_weapon: "Bardiche",
          pregame_ritual:
            "Shaving one half of their mustache for important games.",
          literate: true,
        },
      },
      {
        name: "Shelman McQuoid",
        team: TEAM_NAMES["The Desert Spectres"],
        stats: {
          pass: 58,
          catch: 50,
          run: 53,
          block: 44,
          fight: 54,
          throw: 65,
          luck: 65,
          pronouns: "He/Them",
          civic_engagement: 64,
          alcohol_tolerance: 56,
          favorite_weapon: "Pike",
          pregame_ritual:
            "Consulting a folk rhyme about the weather to predict the game's outcome.",
          literate: true,
        },
      },
      {
        name: "Lovash Marius",
        team: TEAM_NAMES["The Desert Spectres"],
        stats: {
          pass: 52,
          catch: 46,
          run: 42,
          block: 56,
          fight: 43,
          throw: 53,
          luck: 57,
          pronouns: "She/Them",
          civic_engagement: 59,
          alcohol_tolerance: 54,
          favorite_weapon: "War Pick",
          pregame_ritual:
            "Sticking a specific type of feather in their helmet's plume.",
          literate: true,
        },
      },
      {
        name: "Steve",
        team: TEAM_NAMES["The Desert Spectres"],
        stats: {
          pass: 59,
          catch: 63,
          run: 55,
          block: 59,
          fight: 64,
          throw: 48,
          luck: 74,
          pronouns: "She/Her",
          civic_engagement: 42,
          alcohol_tolerance: 57,
          favorite_weapon: "Halberd",
          pregame_ritual:
            "Organizing a small betting pool on who will score first.",
          literate: true,
        },
      },
      {
        name: "Huesman Ring",
        team: TEAM_NAMES["The Desert Spectres"],
        stats: {
          pass: 48,
          catch: 56,
          run: 41,
          block: 48,
          fight: 58,
          throw: 38,
          luck: 44,
          pronouns: "He/Them",
          civic_engagement: 56,
          alcohol_tolerance: 58,
          favorite_weapon: "Military Fork",
          pregame_ritual:
            "Dipping their hands in a bucket of ice-cold well water.",
          literate: true,
        },
      },
    ],
  },
  [TEAM_NAMES["The Haven Lights"]]: {
    name: TEAM_NAMES["The Haven Lights"],
    slug: "haven",
    losses: 0,
    wins: 0,
    score: 0,
    luck: 55,
    sponsor: "Grimble Ironarm",
    stadium: {
      name: "The Aegis Field",
      location: "Haven (Temple of Light Compound)",
      description:
        "A pristine field within the main temple compound, used as the central training ground for the Shield. The pitch is bordered by the library and monastery, and is said to be protected by the twin lights, Dawn's Hope and Silver Twilight.",
      modifiers: ["Hallowed Ground", "Shield's Watch", "Twinlight's Glow"],
    },
    healer: {
      name: "Riffle Harrington",
      team: TEAM_NAMES["The Haven Lights"],
      stats: {
        pass: 56,
        catch: 49,
        run: 49,
        block: 43,
        fight: 66,
        throw: 52,
        luck: 63,
        pronouns: "He/Him",
        civic_engagement: 63,
        alcohol_tolerance: 52,
        favorite_weapon: "Spiked Gauntlet",
        pregame_ritual:
          "Tying their bootlaces together and hopping to the starting line.",
        literate: false,
      },
    },
    players: [
      {
        name: "Shiroma Salim",
        team: TEAM_NAMES["The Haven Lights"],
        stats: {
          pass: 50,
          catch: 51,
          run: 54,
          block: 55,
          fight: 54,
          throw: 62,
          luck: 55,
          pronouns: "He/Him",
          civic_engagement: 51,
          alcohol_tolerance: 60,
          favorite_weapon: "Kirkhammer",
          pregame_ritual: "Re-taping their shield's handle with fresh leather.",
          literate: true,
        },
      },
      {
        name: "Zwart Bunns",
        team: TEAM_NAMES["The Haven Lights"],
        stats: {
          pass: 63,
          catch: 66,
          run: 51,
          block: 51,
          fight: 47,
          throw: 50,
          luck: 53,
          pronouns: "He/Him",
          civic_engagement: 40,
          alcohol_tolerance: 55,
          favorite_weapon: "Cestus",
          pregame_ritual:
            "Whispering a secret fear to the Trollball before the game.",
          literate: false,
        },
      },
      {
        name: "Riffle Heyde",
        team: TEAM_NAMES["The Haven Lights"],
        stats: {
          pass: 55,
          catch: 56,
          run: 48,
          block: 53,
          fight: 50,
          throw: 44,
          luck: 48,
          pronouns: "They/Them",
          civic_engagement: 47,
          alcohol_tolerance: 51,
          favorite_weapon: "Mace",
          pregame_ritual: "Drinking a full waterskin of lukewarm water.",
          literate: true,
        },
      },
      {
        name: "Tybi Reo",
        team: TEAM_NAMES["The Haven Lights"],
        stats: {
          pass: 55,
          catch: 48,
          run: 66,
          block: 56,
          fight: 55,
          throw: 48,
          luck: 50,
          pronouns: "She/Them",
          civic_engagement: 63,
          alcohol_tolerance: 50,
          favorite_weapon: "Mace",
          pregame_ritual:
            "Drawing a detailed, anatomically incorrect diagram of a troll's head.",
          literate: false,
        },
      },
      {
        name: "Berkin Waters",
        team: TEAM_NAMES["The Haven Lights"],
        stats: {
          pass: 51,
          catch: 46,
          run: 58,
          block: 50,
          fight: 54,
          throw: 60,
          luck: 49,
          pronouns: "He/Him",
          civic_engagement: 55,
          alcohol_tolerance: 51,
          favorite_weapon: "Zweihander",
          pregame_ritual:
            "Passing a 'team luckstone' from player to player without speaking.",
          literate: true,
        },
      },
      {
        name: "Farand Keil",
        team: TEAM_NAMES["The Haven Lights"],
        stats: {
          pass: 57,
          catch: 49,
          run: 55,
          block: 37,
          fight: 50,
          throw: 64,
          luck: 48,
          pronouns: "He/Him",
          civic_engagement: 51,
          alcohol_tolerance: 61,
          favorite_weapon: "Whip",
          pregame_ritual:
            "Chewing a specific, bitter root said to improve night vision.",
          literate: true,
        },
      },
      {
        name: "Wieren Ivar",
        team: TEAM_NAMES["The Haven Lights"],
        stats: {
          pass: 66,
          catch: 63,
          run: 52,
          block: 54,
          fight: 64,
          throw: 42,
          luck: 54,
          pronouns: "He/Them",
          civic_engagement: 45,
          alcohol_tolerance: 56,
          favorite_weapon: "Warhammer",
          pregame_ritual:
            "Jogging three laps around the perimeter of the field.",
          literate: false,
        },
      },
      {
        name: "Coward Tarton",
        team: TEAM_NAMES["The Haven Lights"],
        stats: {
          pass: 56,
          catch: 51,
          run: 62,
          block: 47,
          fight: 52,
          throw: 63,
          luck: 51,
          pronouns: "She/Her",
          civic_engagement: 60,
          alcohol_tolerance: 63,
          favorite_weapon: "Tabar",
          pregame_ritual:
            "Kissing their biceps and whispering words of encouragement to them.",
          literate: false,
        },
      },
      {
        name: "Dickenson Beker",
        team: TEAM_NAMES["The Haven Lights"],
        stats: {
          pass: 58,
          catch: 69,
          run: 58,
          block: 53,
          fight: 52,
          throw: 46,
          luck: 63,
          pronouns: "She/Her",
          civic_engagement: 52,
          alcohol_tolerance: 58,
          favorite_weapon: "Billhook",
          pregame_ritual:
            "Trying to teach a stray dog a complicated and useless new trick.",
          literate: true,
        },
      },
      {
        name: "Marlane Lounge",
        team: TEAM_NAMES["The Haven Lights"],
        stats: {
          pass: 64,
          catch: 59,
          run: 54,
          block: 53,
          fight: 52,
          throw: 52,
          luck: 58,
          pronouns: "They/Them",
          civic_engagement: 55,
          alcohol_tolerance: 59,
          favorite_weapon: "Main-gauche",
          pregame_ritual:
            "Challenging a spectator to a game of tic-tac-toe in the dirt.",
          literate: false,
        },
      },
    ],
  },
  [TEAM_NAMES["The Ebon Gate Corruptors"]]: {
    name: TEAM_NAMES["The Ebon Gate Corruptors"],
    slug: "ebon-gate",
    losses: 0,
    wins: 0,
    score: 0,
    luck: 59,
    sponsor: "Demon Lord Orzalon",
    stadium: {
      name: "The Sinking Field",
      location: "Ebon Gate",
      description:
        "A notoriously poorly-maintained stadium built on reclaimed marshland. The ground is unstable, often waterlogged, and sections of the stands are known to collapse.",
      modifiers: ["Thick Mud", "Noxious Fumes", "Sinkhole"],
    },
    healer: {
      name: "Terle Chenay",
      team: TEAM_NAMES["The Ebon Gate Corruptors"],
      stats: {
        pass: 62,
        catch: 64,
        run: 70,
        block: 58,
        fight: 46,
        throw: 62,
        luck: 58,
        pronouns: "She/Her",
        civic_engagement: 55,
        alcohol_tolerance: 54,
        favorite_weapon: "Mace",
        pregame_ritual: "Seeing who on the team can belch the loudest.",
        literate: false,
      },
    },
    players: [
      {
        name: "Bullion Iglesias",
        team: TEAM_NAMES["The Ebon Gate Corruptors"],
        stats: {
          pass: 51,
          catch: 62,
          run: 55,
          block: 52,
          fight: 52,
          throw: 62,
          luck: 57,
          pronouns: "He/Them",
          civic_engagement: 57,
          alcohol_tolerance: 52,
          favorite_weapon: "Axe",
          pregame_ritual:
            "Meditating silently in the corner of the locker room.",
          literate: true,
        },
      },
      {
        name: "Olnek Vizzone",
        team: TEAM_NAMES["The Ebon Gate Corruptors"],
        stats: {
          pass: 54,
          catch: 48,
          run: 53,
          block: 59,
          fight: 49,
          throw: 63,
          luck: 52,
          pronouns: "He/Him",
          civic_engagement: 57,
          alcohol_tolerance: 52,
          favorite_weapon: "Sickle",
          pregame_ritual: "Clapping their hands a prime number of times.",
          literate: true,
        },
      },
      {
        name: "As Utter",
        team: TEAM_NAMES["The Ebon Gate Corruptors"],
        stats: {
          pass: 56,
          catch: 57,
          run: 48,
          block: 50,
          fight: 67,
          throw: 38,
          luck: 51,
          pronouns: "He/Him",
          civic_engagement: 70,
          alcohol_tolerance: 61,
          favorite_weapon: "Greatsword",
          pregame_ritual:
            "Insisting on being the last player to leave the locker room.",
          literate: true,
        },
      },
      {
        name: "Smith Syst",
        team: TEAM_NAMES["The Ebon Gate Corruptors"],
        stats: {
          pass: 51,
          catch: 59,
          run: 49,
          block: 47,
          fight: 63,
          throw: 59,
          luck: 52,
          pronouns: "She/Her",
          civic_engagement: 54,
          alcohol_tolerance: 51,
          favorite_weapon: "Voulge",
          pregame_ritual: "Daring a teammate to eat a live worm.",
          literate: true,
        },
      },
      {
        name: "Napoleon Anzovin",
        team: TEAM_NAMES["The Ebon Gate Corruptors"],
        stats: {
          pass: 50,
          catch: 63,
          run: 52,
          block: 45,
          fight: 59,
          throw: 49,
          luck: 57,
          pronouns: "He/Him",
          civic_engagement: 57,
          alcohol_tolerance: 58,
          favorite_weapon: "Kirkhammer",
          pregame_ritual:
            "Thanking their armor for the protection it's about to offer.",
          literate: true,
        },
      },
      {
        name: "Simsar Carrelli",
        team: TEAM_NAMES["The Ebon Gate Corruptors"],
        stats: {
          pass: 68,
          catch: 54,
          run: 53,
          block: 56,
          fight: 53,
          throw: 49,
          luck: 68,
          pronouns: "He/Him",
          civic_engagement: 63,
          alcohol_tolerance: 56,
          favorite_weapon: "Billhook",
          pregame_ritual: "Counting the number of clouds in the sky.",
          literate: true,
        },
      },
      {
        name: "Ahasuerus An",
        team: TEAM_NAMES["The Ebon Gate Corruptors"],
        stats: {
          pass: 39,
          catch: 56,
          run: 49,
          block: 61,
          fight: 51,
          throw: 63,
          luck: 55,
          pronouns: "She/Them",
          civic_engagement: 55,
          alcohol_tolerance: 64,
          favorite_weapon: "Talwar",
          pregame_ritual:
            "Tapping each piece of their armor in a specific sequence.",
          literate: false,
        },
      },
      {
        name: "Ellette Paz",
        team: TEAM_NAMES["The Ebon Gate Corruptors"],
        stats: {
          pass: 54,
          catch: 49,
          run: 54,
          block: 65,
          fight: 54,
          throw: 66,
          luck: 44,
          pronouns: "She/Them",
          civic_engagement: 51,
          alcohol_tolerance: 54,
          favorite_weapon: "Blackjack",
          pregame_ritual:
            "Insisting on being the last player to leave the locker room.",
          literate: false,
        },
      },
      {
        name: "Judi Carrington",
        team: TEAM_NAMES["The Ebon Gate Corruptors"],
        stats: {
          pass: 61,
          catch: 53,
          run: 58,
          block: 53,
          fight: 55,
          throw: 56,
          luck: 45,
          pronouns: "He/Him",
          civic_engagement: 54,
          alcohol_tolerance: 54,
          favorite_weapon: "Estoc",
          pregame_ritual: "Singing a sea shanty completely out of tune.",
          literate: true,
        },
      },
      {
        name: "Amedeo Bari",
        team: TEAM_NAMES["The Ebon Gate Corruptors"],
        stats: {
          pass: 60,
          catch: 54,
          run: 67,
          block: 53,
          fight: 53,
          throw: 53,
          luck: 45,
          pronouns: "He/Him",
          civic_engagement: 46,
          alcohol_tolerance: 51,
          favorite_weapon: "Rapier",
          pregame_ritual: "Polishing their boots with bacon grease.",
          literate: false,
        },
      },
    ],
  },
  [TEAM_NAMES["The New Monteforte Chaos Creatures"]]: {
    name: TEAM_NAMES["The New Monteforte Chaos Creatures"],
    slug: "new-monteforte",
    losses: 0,
    wins: 0,
    score: 0,
    luck: 65,
    sponsor: "The White Ravens",
    stadium: {
      name: "The Unruly Yard",
      location: "New Monteforte",
      description:
        "A field in the center of the city's most rebellious district. The stadium is covered in graffiti, the crowd is hostile, and riots are a common post-game (and mid-game) event.",
      modifiers: ["Rowdy Crowd", "Unstable Scaffolding", "Street Performer"],
    },
    healer: {
      name: "Lian Denton",
      team: TEAM_NAMES["The New Monteforte Chaos Creatures"],
      stats: {
        pass: 55,
        catch: 62,
        run: 56,
        block: 58,
        fight: 45,
        throw: 60,
        luck: 50,
        pronouns: "They/Them",
        civic_engagement: 52,
        alcohol_tolerance: 66,
        favorite_weapon: "Battle Axe",
        pregame_ritual: "Drinking a shot of hot gravy from a dented tin cup.",
        literate: false,
      },
    },
    players: [
      {
        name: "Boulanger Procto",
        team: TEAM_NAMES["The New Monteforte Chaos Creatures"],
        stats: {
          pass: 53,
          catch: 48,
          run: 57,
          block: 66,
          fight: 60,
          throw: 57,
          luck: 54,
          pronouns: "He/Him",
          civic_engagement: 49,
          alcohol_tolerance: 45,
          favorite_weapon: "Broadsword",
          pregame_ritual:
            "Arranging their gear in a perfect, aesthetically pleasing spiral.",
          literate: true,
        },
      },
      {
        name: "Urata Oriana",
        team: TEAM_NAMES["The New Monteforte Chaos Creatures"],
        stats: {
          pass: 46,
          catch: 42,
          run: 49,
          block: 49,
          fight: 52,
          throw: 54,
          luck: 50,
          pronouns: "He/Them",
          civic_engagement: 54,
          alcohol_tolerance: 56,
          favorite_weapon: "Zweihander",
          pregame_ritual:
            "Testing the heft of their weapon with a series of slow, deliberate swings.",
          literate: true,
        },
      },
      {
        name: "Gabriele Klehm",
        team: TEAM_NAMES["The New Monteforte Chaos Creatures"],
        stats: {
          pass: 59,
          catch: 57,
          run: 47,
          block: 62,
          fight: 50,
          throw: 56,
          luck: 55,
          pronouns: "She/Them",
          civic_engagement: 66,
          alcohol_tolerance: 50,
          favorite_weapon: "Quarterstaff",
          pregame_ritual: "Kissing the Trollball on its stitched 'nose'.",
          literate: true,
        },
      },
      {
        name: "Tucker Hett",
        team: TEAM_NAMES["The New Monteforte Chaos Creatures"],
        stats: {
          pass: 50,
          catch: 50,
          run: 49,
          block: 59,
          fight: 52,
          throw: 61,
          luck: 42,
          pronouns: "She/Them",
          civic_engagement: 46,
          alcohol_tolerance: 57,
          favorite_weapon: "Billhook",
          pregame_ritual: "Reviewing hand signals for secret plays.",
          literate: true,
        },
      },
      {
        name: "Mouldon Earl",
        team: TEAM_NAMES["The New Monteforte Chaos Creatures"],
        stats: {
          pass: 55,
          catch: 55,
          run: 63,
          block: 56,
          fight: 44,
          throw: 55,
          luck: 57,
          pronouns: "They/Them",
          civic_engagement: 51,
          alcohol_tolerance: 52,
          favorite_weapon: "Rondel Dagger",
          pregame_ritual:
            "Refusing to step on any lines on the field before the whistle blows.",
          literate: true,
        },
      },
      {
        name: "Placido Kora",
        team: TEAM_NAMES["The New Monteforte Chaos Creatures"],
        stats: {
          pass: 67,
          catch: 59,
          run: 48,
          block: 52,
          fight: 56,
          throw: 46,
          luck: 46,
          pronouns: "She/Her",
          civic_engagement: 47,
          alcohol_tolerance: 45,
          favorite_weapon: "Seax",
          pregame_ritual:
            "Telling a terrible joke to the Trollball to 'loosen it up'.",
          literate: true,
        },
      },
      {
        name: "Alben Diantha",
        team: TEAM_NAMES["The New Monteforte Chaos Creatures"],
        stats: {
          pass: 53,
          catch: 54,
          run: 48,
          block: 55,
          fight: 63,
          throw: 65,
          luck: 52,
          pronouns: "He/Him",
          civic_engagement: 52,
          alcohol_tolerance: 57,
          favorite_weapon: "Hammer",
          pregame_ritual:
            "Dipping their hands in a bucket of ice-cold well water.",
          literate: true,
        },
      },
      {
        name: "Fogel Raynold",
        team: TEAM_NAMES["The New Monteforte Chaos Creatures"],
        stats: {
          pass: 48,
          catch: 48,
          run: 54,
          block: 54,
          fight: 48,
          throw: 57,
          luck: 60,
          pronouns: "He/Them",
          civic_engagement: 61,
          alcohol_tolerance: 55,
          favorite_weapon: "Horseman's Pick",
          pregame_ritual: "Slapping their own helmet until their ears ring.",
          literate: true,
        },
      },
      {
        name: "Wolbrom Ariella",
        team: TEAM_NAMES["The New Monteforte Chaos Creatures"],
        stats: {
          pass: 63,
          catch: 71,
          run: 59,
          block: 40,
          fight: 60,
          throw: 58,
          luck: 72,
          pronouns: "He/Them",
          civic_engagement: 45,
          alcohol_tolerance: 53,
          favorite_weapon: "Scythe",
          pregame_ritual: "Singing a sea shanty completely out of tune.",
          literate: false,
        },
      },
      {
        name: "Raouf Dragone",
        team: TEAM_NAMES["The New Monteforte Chaos Creatures"],
        stats: {
          pass: 48,
          catch: 61,
          run: 52,
          block: 44,
          fight: 50,
          throw: 61,
          luck: 52,
          pronouns: "They/Them",
          civic_engagement: 63,
          alcohol_tolerance: 61,
          favorite_weapon: "Trident",
          pregame_ritual: "Reciting a short, epic poem about a past victory.",
          literate: false,
        },
      },
    ],
  },
  [TEAM_NAMES["The New Prosperity Profits"]]: {
    name: TEAM_NAMES["The New Prosperity Profits"],
    slug: "new-prosperity",
    losses: 0,
    wins: 0,
    score: 0,
    luck: 50,
    sponsor: "The Church of Pecune",
    stadium: {
      name: "The Guilder's Field",
      location: "New Prosperity",
      description:
        "An opulent stadium sponsored by the powerful Church of Pecune. The stands feature luxurious, velvet-lined boxes for bankers, who are often more focused on making deals than the game.",
      modifiers: ["Hostile Takeover", "Hired Hecklers", "Market Fluctuation"],
    },
    healer: {
      name: "Merissa Mathian",
      team: TEAM_NAMES["The New Prosperity Profits"],
      stats: {
        pass: 54,
        catch: 54,
        run: 53,
        block: 45,
        fight: 52,
        throw: 59,
        luck: 49,
        pronouns: "She/Her",
        civic_engagement: 66,
        alcohol_tolerance: 51,
        favorite_weapon: "Longsword",
        pregame_ritual: "Washing their hands with dirt.",
        literate: true,
      },
    },
    players: [
      {
        name: "Pulchi Benyamin",
        team: TEAM_NAMES["The New Prosperity Profits"],
        stats: {
          pass: 54,
          catch: 63,
          run: 67,
          block: 63,
          fight: 47,
          throw: 44,
          luck: 56,
          pronouns: "She/Them",
          civic_engagement: 59,
          alcohol_tolerance: 54,
          favorite_weapon: "Swordstaff",
          pregame_ritual: "Eating a dandelion, stem and all.",
          literate: true,
        },
      },
      {
        name: "Boleslaw Heathcote",
        team: TEAM_NAMES["The New Prosperity Profits"],
        stats: {
          pass: 60,
          catch: 48,
          run: 51,
          block: 58,
          fight: 48,
          throw: 47,
          luck: 56,
          pronouns: "She/Her",
          civic_engagement: 53,
          alcohol_tolerance: 56,
          favorite_weapon: "Zweihander",
          pregame_ritual:
            "Lighting a small piece of parchment on fire and inhaling the smoke.",
          literate: false,
        },
      },
      {
        name: "Gladdie Farika",
        team: TEAM_NAMES["The New Prosperity Profits"],
        stats: {
          pass: 48,
          catch: 48,
          run: 60,
          block: 54,
          fight: 58,
          throw: 59,
          luck: 51,
          pronouns: "They/Them",
          civic_engagement: 77,
          alcohol_tolerance: 62,
          favorite_weapon: "Morning Star",
          pregame_ritual:
            "Meticulously cleaning each stud on their boots with a special brush.",
          literate: true,
        },
      },
      {
        name: "Yoshi Cathy",
        team: TEAM_NAMES["The New Prosperity Profits"],
        stats: {
          pass: 47,
          catch: 50,
          run: 56,
          block: 60,
          fight: 74,
          throw: 57,
          luck: 58,
          pronouns: "He/Them",
          civic_engagement: 54,
          alcohol_tolerance: 50,
          favorite_weapon: "Spear",
          pregame_ritual: "Eating a raw onion, layer by layer, without crying.",
          literate: false,
        },
      },
      {
        name: "Aufmann Tedric",
        team: TEAM_NAMES["The New Prosperity Profits"],
        stats: {
          pass: 62,
          catch: 51,
          run: 61,
          block: 55,
          fight: 55,
          throw: 58,
          luck: 54,
          pronouns: "She/Them",
          civic_engagement: 62,
          alcohol_tolerance: 58,
          favorite_weapon: "Dane Axe",
          pregame_ritual:
            "Getting a teammate to pour a bucket of cold water over their head.",
          literate: true,
        },
      },
      {
        name: "Krueger Jacinthe",
        team: TEAM_NAMES["The New Prosperity Profits"],
        stats: {
          pass: 61,
          catch: 53,
          run: 49,
          block: 57,
          fight: 59,
          throw: 47,
          luck: 53,
          pronouns: "He/Him",
          civic_engagement: 44,
          alcohol_tolerance: 42,
          favorite_weapon: "Spear",
          pregame_ritual:
            "A team-wide moment of absolute silence to 'gather their thoughts'.",
          literate: false,
        },
      },
      {
        name: "Abramson Doxia",
        team: TEAM_NAMES["The New Prosperity Profits"],
        stats: {
          pass: 51,
          catch: 61,
          run: 53,
          block: 57,
          fight: 55,
          throw: 45,
          luck: 50,
          pronouns: "He/Them",
          civic_engagement: 66,
          alcohol_tolerance: 70,
          favorite_weapon: "Arming Sword",
          pregame_ritual:
            "Sharpening the edges of their blunted weapon (an exercise in futility).",
          literate: true,
        },
      },
      {
        name: "Milman Galvan",
        team: TEAM_NAMES["The New Prosperity Profits"],
        stats: {
          pass: 51,
          catch: 66,
          run: 56,
          block: 50,
          fight: 52,
          throw: 68,
          luck: 56,
          pronouns: "She/Them",
          civic_engagement: 60,
          alcohol_tolerance: 62,
          favorite_weapon: "Boar Spear",
          pregame_ritual: "Humming a tune they believe only they know.",
          literate: false,
        },
      },
      {
        name: "Faina Hendrix",
        team: TEAM_NAMES["The New Prosperity Profits"],
        stats: {
          pass: 52,
          catch: 55,
          run: 63,
          block: 67,
          fight: 53,
          throw: 57,
          luck: 56,
          pronouns: "He/Him",
          civic_engagement: 54,
          alcohol_tolerance: 65,
          favorite_weapon: "Greatsword",
          pregame_ritual:
            "Lighting a small piece of parchment on fire and inhaling the smoke.",
          literate: true,
        },
      },
      {
        name: "Pellikka Concettina",
        team: TEAM_NAMES["The New Prosperity Profits"],
        stats: {
          pass: 64,
          catch: 44,
          run: 58,
          block: 62,
          fight: 54,
          throw: 51,
          luck: 58,
          pronouns: "He/Him",
          civic_engagement: 53,
          alcohol_tolerance: 53,
          favorite_weapon: "Spear",
          pregame_ritual:
            "Avoiding eye contact with anyone wearing the color green.",
          literate: true,
        },
      },
    ],
  },
  [TEAM_NAMES["The New Ravenfall Commanders"]]: {
    name: TEAM_NAMES["The New Ravenfall Commanders"],
    slug: "new-ravenfall",
    losses: 0,
    wins: 0,
    score: 0,
    luck: 64,
    sponsor: "The Kingdom of Eponore",
    stadium: {
      name: "The Stronghold Bailey",
      location: "New Ravenfall (Stronghold Castle)",
      description:
        "The team plays in the central bailey of Stronghold Castle, a massive fortress built on a plateau overlooking the city. The field is packed earth and cobblestone, and the crowd watches from the surrounding stone ramparts.",
      modifiers: ["Cobblestone Pitch", "Rampart Shadows", "Castle Echo"],
    },
    healer: {
      name: "Hooge Imtiaz",
      team: TEAM_NAMES["The New Ravenfall Commanders"],
      stats: {
        pass: 57,
        catch: 50,
        run: 39,
        block: 59,
        fight: 53,
        throw: 63,
        luck: 59,
        pronouns: "She/Her",
        civic_engagement: 56,
        alcohol_tolerance: 44,
        favorite_weapon: "Warhammer",
        pregame_ritual:
          "Leading the team in a synchronized chant that slowly gets louder.",
        literate: true,
      },
    },
    players: [
      {
        name: "Dusa Curson",
        team: TEAM_NAMES["The New Ravenfall Commanders"],
        stats: {
          pass: 47,
          catch: 52,
          run: 55,
          block: 56,
          fight: 59,
          throw: 41,
          luck: 57,
          pronouns: "She/Them",
          civic_engagement: 48,
          alcohol_tolerance: 51,
          favorite_weapon: "Hatchet",
          pregame_ritual:
            "Searching for a four-leaf clover near the sidelines.",
          literate: false,
        },
      },
      {
        name: "Moir Sass",
        team: TEAM_NAMES["The New Ravenfall Commanders"],
        stats: {
          pass: 58,
          catch: 50,
          run: 51,
          block: 48,
          fight: 60,
          throw: 56,
          luck: 61,
          pronouns: "They/Them",
          civic_engagement: 55,
          alcohol_tolerance: 53,
          favorite_weapon: "Trident",
          pregame_ritual: "Reciting a short, epic poem about a past victory.",
          literate: true,
        },
      },
      {
        name: "Theis Loredo",
        team: TEAM_NAMES["The New Ravenfall Commanders"],
        stats: {
          pass: 56,
          catch: 46,
          run: 55,
          block: 54,
          fight: 62,
          throw: 61,
          luck: 59,
          pronouns: "She/Them",
          civic_engagement: 49,
          alcohol_tolerance: 49,
          favorite_weapon: "Claymore",
          pregame_ritual: "Sharing a piece of fermented fish with a teammate.",
          literate: true,
        },
      },
      {
        name: "Fleme Alis",
        team: TEAM_NAMES["The New Ravenfall Commanders"],
        stats: {
          pass: 52,
          catch: 53,
          run: 52,
          block: 61,
          fight: 63,
          throw: 58,
          luck: 48,
          pronouns: "He/Him",
          civic_engagement: 57,
          alcohol_tolerance: 46,
          favorite_weapon: "Glaive",
          pregame_ritual:
            "Listening to the wind for a sign of which way the game will turn.",
          literate: true,
        },
      },
      {
        name: "Estes Adrian",
        team: TEAM_NAMES["The New Ravenfall Commanders"],
        stats: {
          pass: 56,
          catch: 52,
          run: 54,
          block: 54,
          fight: 51,
          throw: 49,
          luck: 68,
          pronouns: "He/Them",
          civic_engagement: 54,
          alcohol_tolerance: 60,
          favorite_weapon: "Katar",
          pregame_ritual:
            "Eating a piece of honeycomb to 'sweeten' their victory.",
          literate: false,
        },
      },
      {
        name: "Rhett Gavrilla",
        team: TEAM_NAMES["The New Ravenfall Commanders"],
        stats: {
          pass: 68,
          catch: 64,
          run: 53,
          block: 56,
          fight: 68,
          throw: 59,
          luck: 59,
          pronouns: "They/Them",
          civic_engagement: 56,
          alcohol_tolerance: 59,
          favorite_weapon: "Woodsman's Axe",
          pregame_ritual:
            "Collecting a pebble from every field they've ever played on.",
          literate: true,
        },
      },
      {
        name: "Jessalin Zobias",
        team: TEAM_NAMES["The New Ravenfall Commanders"],
        stats: {
          pass: 57,
          catch: 54,
          run: 55,
          block: 42,
          fight: 52,
          throw: 53,
          luck: 56,
          pronouns: "He/Him",
          civic_engagement: 54,
          alcohol_tolerance: 53,
          favorite_weapon: "Military Fork",
          pregame_ritual: "Tugging on their left earlobe three times.",
          literate: true,
        },
      },
      {
        name: "Jozef Pepe",
        team: TEAM_NAMES["The New Ravenfall Commanders"],
        stats: {
          pass: 50,
          catch: 56,
          run: 60,
          block: 43,
          fight: 50,
          throw: 49,
          luck: 55,
          pronouns: "He/Him",
          civic_engagement: 64,
          alcohol_tolerance: 54,
          favorite_weapon: "Zweihander",
          pregame_ritual: "Seeing who on the team can belch the loudest.",
          literate: true,
        },
      },
      {
        name: "Croteau Osmo",
        team: TEAM_NAMES["The New Ravenfall Commanders"],
        stats: {
          pass: 68,
          catch: 51,
          run: 55,
          block: 50,
          fight: 62,
          throw: 52,
          luck: 54,
          pronouns: "She/Her",
          civic_engagement: 45,
          alcohol_tolerance: 66,
          favorite_weapon: "Broadsword",
          pregame_ritual: "Tying a red string around their pinky finger.",
          literate: true,
        },
      },
      {
        name: "Pirozzo Opal",
        team: TEAM_NAMES["The New Ravenfall Commanders"],
        stats: {
          pass: 47,
          catch: 58,
          run: 54,
          block: 51,
          fight: 51,
          throw: 53,
          luck: 57,
          pronouns: "He/Them",
          civic_engagement: 63,
          alcohol_tolerance: 55,
          favorite_weapon: "Kriegsmesser",
          pregame_ritual: "Sharing a piece of fermented fish with a teammate.",
          literate: true,
        },
      },
    ],
  },
  [TEAM_NAMES["The Southport Narwhals"]]: {
    name: TEAM_NAMES["The Southport Narwhals"],
    slug: "southport",
    losses: 0,
    wins: 0,
    score: 0,
    luck: 48,
    sponsor: "Grimfrost",
    stadium: {
      name: "The Cliffside Pitch",
      location: "Southport",
      description:
        "A perilous, windswept field built next to the town's lighthouse. There is no ocean-side barrier, and the wind is notoriously unpredictable. The tusk-like lighthouse is the only landmark.",
      modifiers: ["Gale-Force Winds", "Sea Spray", "Rocky Outcropping"],
    },
    healer: {
      name: "Sand Denys",
      team: TEAM_NAMES["The Southport Narwhals"],
      stats: {
        pass: 55,
        catch: 54,
        run: 50,
        block: 53,
        fight: 61,
        throw: 64,
        luck: 60,
        pronouns: "She/Her",
        civic_engagement: 68,
        alcohol_tolerance: 46,
        favorite_weapon: "Cestus",
        pregame_ritual:
          "Telling each other exaggerated lies about their own strength.",
        literate: false,
      },
    },
    players: [
      {
        name: "Blood Eppes",
        team: TEAM_NAMES["The Southport Narwhals"],
        stats: {
          pass: 56,
          catch: 54,
          run: 52,
          block: 47,
          fight: 64,
          throw: 63,
          luck: 54,
          pronouns: "He/Him",
          civic_engagement: 60,
          alcohol_tolerance: 56,
          favorite_weapon: "Cutlass",
          pregame_ritual:
            "Stretching their hamstrings for exactly seven minutes.",
          literate: false,
        },
      },
      {
        name: "Malcolm Goer",
        team: TEAM_NAMES["The Southport Narwhals"],
        stats: {
          pass: 56,
          catch: 36,
          run: 63,
          block: 65,
          fight: 56,
          throw: 58,
          luck: 59,
          pronouns: "They/Them",
          civic_engagement: 63,
          alcohol_tolerance: 55,
          favorite_weapon: "Morning Star",
          pregame_ritual: "Rubbing the Trollball on their armpits for 'grip'.",
          literate: true,
        },
      },
      {
        name: "Blanc Fantasia",
        team: TEAM_NAMES["The Southport Narwhals"],
        stats: {
          pass: 51,
          catch: 51,
          run: 60,
          block: 58,
          fight: 64,
          throw: 52,
          luck: 52,
          pronouns: "He/Them",
          civic_engagement: 43,
          alcohol_tolerance: 53,
          favorite_weapon: "Seax",
          pregame_ritual:
            "Arranging their gear in a perfect, aesthetically pleasing spiral.",
          literate: true,
        },
      },
      {
        name: "Loralyn Lyndy",
        team: TEAM_NAMES["The Southport Narwhals"],
        stats: {
          pass: 58,
          catch: 47,
          run: 58,
          block: 57,
          fight: 57,
          throw: 59,
          luck: 61,
          pronouns: "She/Them",
          civic_engagement: 49,
          alcohol_tolerance: 53,
          favorite_weapon: "Main-gauche",
          pregame_ritual:
            "Adjusting their codpiece with theatrical importance.",
          literate: true,
        },
      },
      {
        name: "Cibis Areta",
        team: TEAM_NAMES["The Southport Narwhals"],
        stats: {
          pass: 63,
          catch: 48,
          run: 57,
          block: 59,
          fight: 54,
          throw: 45,
          luck: 56,
          pronouns: "She/Them",
          civic_engagement: 61,
          alcohol_tolerance: 71,
          favorite_weapon: "Estoc",
          pregame_ritual:
            "Getting a teammate to pour a bucket of cold water over their head.",
          literate: true,
        },
      },
      {
        name: "Braden Gaile",
        team: TEAM_NAMES["The Southport Narwhals"],
        stats: {
          pass: 47,
          catch: 52,
          run: 53,
          block: 67,
          fight: 68,
          throw: 65,
          luck: 53,
          pronouns: "He/Them",
          civic_engagement: 57,
          alcohol_tolerance: 62,
          favorite_weapon: "Swordstaff",
          pregame_ritual:
            "Muttering a nonsensical rhyme to ward off bad spirits.",
          literate: true,
        },
      },
      {
        name: "Crescint Sonia",
        team: TEAM_NAMES["The Southport Narwhals"],
        stats: {
          pass: 65,
          catch: 64,
          run: 67,
          block: 47,
          fight: 44,
          throw: 53,
          luck: 59,
          pronouns: "He/Him",
          civic_engagement: 57,
          alcohol_tolerance: 54,
          favorite_weapon: "Warhammer",
          pregame_ritual: "Filing down a single fingernail into a sharp point.",
          literate: true,
        },
      },
      {
        name: "Cilurzo Sochor",
        team: TEAM_NAMES["The Southport Narwhals"],
        stats: {
          pass: 58,
          catch: 43,
          run: 54,
          block: 65,
          fight: 66,
          throw: 53,
          luck: 53,
          pronouns: "He/Him",
          civic_engagement: 60,
          alcohol_tolerance: 53,
          favorite_weapon: "Hatchet",
          pregame_ritual:
            "Giving the Trollball a heroic backstory before each game.",
          literate: true,
        },
      },
      {
        name: "Torey Dannye",
        team: TEAM_NAMES["The Southport Narwhals"],
        stats: {
          pass: 49,
          catch: 59,
          run: 55,
          block: 56,
          fight: 45,
          throw: 57,
          luck: 60,
          pronouns: "He/Him",
          civic_engagement: 51,
          alcohol_tolerance: 61,
          favorite_weapon: "Swordstaff",
          pregame_ritual:
            "Listening to the wind for a sign of which way the game will turn.",
          literate: true,
        },
      },
      {
        name: "Fineman Dolhenty",
        team: TEAM_NAMES["The Southport Narwhals"],
        stats: {
          pass: 51,
          catch: 49,
          run: 60,
          block: 55,
          fight: 54,
          throw: 48,
          luck: 48,
          pronouns: "She/Her",
          civic_engagement: 51,
          alcohol_tolerance: 55,
          favorite_weapon: "Kirkhammer",
          pregame_ritual: "Wearing a necklace of polished river stones.",
          literate: true,
        },
      },
    ],
  },
  [TEAM_NAMES["The Tortell Privateers"]]: {
    name: TEAM_NAMES["The Tortell Privateers"],
    slug: "tortell",
    losses: 0,
    wins: 0,
    score: 0,
    luck: 48,
    sponsor: "Cedar Hill",
    stadium: {
      name: "The Buccaneer's Bowl",
      location: "Toast Island Resort",
      description:
        "A flashy, pristine stadium built on a private beach exclusively for resort guests. The field is imported turf, and a massive, puppet kraken in the bay entertains the crowd at halftime.",
      modifiers: ["Distracted Tourists", "Blinding Sun", "Resort Security"],
    },
    healer: {
      name: "Eugen Zacks",
      team: TEAM_NAMES["The Tortell Privateers"],
      stats: {
        pass: 55,
        catch: 60,
        run: 55,
        block: 51,
        fight: 65,
        throw: 65,
        luck: 52,
        pronouns: "He/Him",
        civic_engagement: 64,
        alcohol_tolerance: 55,
        favorite_weapon: "Swordstaff",
        pregame_ritual: "Slapping their own helmet until their ears ring.",
        literate: true,
      },
    },
    players: [
      {
        name: "Lilithe Royce",
        team: TEAM_NAMES["The Tortell Privateers"],
        stats: {
          pass: 52,
          catch: 59,
          run: 59,
          block: 51,
          fight: 49,
          throw: 57,
          luck: 52,
          pronouns: "She/Them",
          civic_engagement: 57,
          alcohol_tolerance: 51,
          favorite_weapon: "Mace",
          pregame_ritual:
            "Sticking leeches to their legs to 'lighten their step'.",
          literate: false,
        },
      },
      {
        name: "Castorina Gies",
        team: TEAM_NAMES["The Tortell Privateers"],
        stats: {
          pass: 48,
          catch: 65,
          run: 66,
          block: 52,
          fight: 59,
          throw: 51,
          luck: 56,
          pronouns: "He/Him",
          civic_engagement: 56,
          alcohol_tolerance: 55,
          favorite_weapon: "Sickle",
          pregame_ritual:
            "Bribing a local oracle with a meat pie for a vague prophecy.",
          literate: true,
        },
      },
      {
        name: "Melisande Eustacia",
        team: TEAM_NAMES["The Tortell Privateers"],
        stats: {
          pass: 70,
          catch: 59,
          run: 53,
          block: 61,
          fight: 61,
          throw: 39,
          luck: 52,
          pronouns: "He/Him",
          civic_engagement: 44,
          alcohol_tolerance: 64,
          favorite_weapon: "Talwar",
          pregame_ritual: "Reviewing hand signals for secret plays.",
          literate: false,
        },
      },
      {
        name: "Loralee Sunny",
        team: TEAM_NAMES["The Tortell Privateers"],
        stats: {
          pass: 46,
          catch: 54,
          run: 60,
          block: 59,
          fight: 53,
          throw: 55,
          luck: 66,
          pronouns: "She/Them",
          civic_engagement: 47,
          alcohol_tolerance: 63,
          favorite_weapon: "War Scythe",
          pregame_ritual:
            "Reading their own fortune in a scattering of knuckle bones.",
          literate: true,
        },
      },
      {
        name: "Kidder Starkey",
        team: TEAM_NAMES["The Tortell Privateers"],
        stats: {
          pass: 50,
          catch: 59,
          run: 65,
          block: 64,
          fight: 57,
          throw: 58,
          luck: 53,
          pronouns: "He/Them",
          civic_engagement: 52,
          alcohol_tolerance: 54,
          favorite_weapon: "Rapier",
          pregame_ritual:
            "Thanking their armor for the protection it's about to offer.",
          literate: false,
        },
      },
      {
        name: "Keisling Damalas",
        team: TEAM_NAMES["The Tortell Privateers"],
        stats: {
          pass: 56,
          catch: 55,
          run: 53,
          block: 63,
          fight: 64,
          throw: 63,
          luck: 46,
          pronouns: "He/Them",
          civic_engagement: 65,
          alcohol_tolerance: 57,
          favorite_weapon: "Rondel Dagger",
          pregame_ritual:
            "Painting their teeth with a mixture of charcoal and water.",
          literate: false,
        },
      },
      {
        name: "Goldberg Tova",
        team: TEAM_NAMES["The Tortell Privateers"],
        stats: {
          pass: 50,
          catch: 58,
          run: 62,
          block: 65,
          fight: 66,
          throw: 54,
          luck: 65,
          pronouns: "She/Them",
          civic_engagement: 60,
          alcohol_tolerance: 52,
          favorite_weapon: "Glaive",
          pregame_ritual:
            "Doing a series of loud, guttural breathing exercises.",
          literate: false,
        },
      },
      {
        name: "Ellan Elburt",
        team: TEAM_NAMES["The Tortell Privateers"],
        stats: {
          pass: 51,
          catch: 57,
          run: 54,
          block: 50,
          fight: 64,
          throw: 59,
          luck: 44,
          pronouns: "He/Them",
          civic_engagement: 48,
          alcohol_tolerance: 44,
          favorite_weapon: "Tabar",
          pregame_ritual:
            "Reciting their grocery list backward to clear their mind.",
          literate: true,
        },
      },
      {
        name: "Payson Jan",
        team: TEAM_NAMES["The Tortell Privateers"],
        stats: {
          pass: 54,
          catch: 52,
          run: 60,
          block: 56,
          fight: 59,
          throw: 63,
          luck: 55,
          pronouns: "He/Him",
          civic_engagement: 63,
          alcohol_tolerance: 46,
          favorite_weapon: "Tabar",
          pregame_ritual: "Clapping their hands a prime number of times.",
          literate: true,
        },
      },
      {
        name: "Dib Tufts",
        team: TEAM_NAMES["The Tortell Privateers"],
        stats: {
          pass: 63,
          catch: 60,
          run: 57,
          block: 59,
          fight: 58,
          throw: 62,
          luck: 58,
          pronouns: "He/Them",
          civic_engagement: 49,
          alcohol_tolerance: 48,
          favorite_weapon: "Axe",
          pregame_ritual: "Chugging a raw egg, shell and all.",
          literate: true,
        },
      },
    ],
  },
  [TEAM_NAMES["The Zmeigorod Snessengers"]]: {
    name: TEAM_NAMES["The Zmeigorod Snessengers"],
    slug: "zmeigorod",
    losses: 0,
    wins: 0,
    score: 0,
    luck: 53,
    sponsor: "The Grove",
    stadium: {
      name: "The Serpent's Pass",
      location: "Zmeigorod, just west of the lumber mill",
      modifiers: ["Altitude Sickness", "Sudden Downpour", "Rockslide"],
      description:
        "Has to be periodically rebuilt whenever the old stadium starts sinking into the swamp. Don’t worry about it.",
    },
    healer: {
      name: "Waldon Tadeo",
      team: TEAM_NAMES["The Zmeigorod Snessengers"],
      stats: {
        pass: 56,
        catch: 65,
        run: 55,
        block: 56,
        fight: 54,
        throw: 60,
        luck: 50,
        pronouns: "She/Them",
        civic_engagement: 56,
        alcohol_tolerance: 53,
        favorite_weapon: "Battle Axe",
        pregame_ritual:
          "Rubbing a foul-smelling local mushroom on their elbows for flexibility.",
        literate: false,
      },
    },
    players: [
      {
        name: "Delija Dowling",
        team: TEAM_NAMES["The Zmeigorod Snessengers"],
        stats: {
          pass: 47,
          catch: 55,
          run: 50,
          block: 51,
          fight: 53,
          throw: 56,
          luck: 58,
          pronouns: "He/Him",
          civic_engagement: 60,
          alcohol_tolerance: 61,
          favorite_weapon: "Seax",
          pregame_ritual: "Chugging a raw egg, shell and all.",
          literate: true,
        },
      },
      {
        name: "Northway Orran",
        team: TEAM_NAMES["The Zmeigorod Snessengers"],
        stats: {
          pass: 54,
          catch: 49,
          run: 60,
          block: 55,
          fight: 66,
          throw: 53,
          luck: 53,
          pronouns: "She/Them",
          civic_engagement: 58,
          alcohol_tolerance: 59,
          favorite_weapon: "Machete",
          pregame_ritual:
            "Performing a series of aggressive, theatrical poses.",
          literate: false,
        },
      },
      {
        name: "Evalyn Pierrepont",
        team: TEAM_NAMES["The Zmeigorod Snessengers"],
        stats: {
          pass: 57,
          catch: 49,
          run: 66,
          block: 54,
          fight: 48,
          throw: 50,
          luck: 53,
          pronouns: "He/Him",
          civic_engagement: 53,
          alcohol_tolerance: 66,
          favorite_weapon: "Seax",
          pregame_ritual:
            "Polishing their helmet with a live snail for good luck.",
          literate: false,
        },
      },
      {
        name: "Rose Kluge",
        team: TEAM_NAMES["The Zmeigorod Snessengers"],
        stats: {
          pass: 51,
          catch: 54,
          run: 63,
          block: 49,
          fight: 52,
          throw: 52,
          luck: 55,
          pronouns: "She/Her",
          civic_engagement: 53,
          alcohol_tolerance: 46,
          favorite_weapon: "Cudgel",
          pregame_ritual:
            "Tensing every muscle in their body at once, then releasing.",
          literate: false,
        },
      },
      {
        name: "Gere Cordelie",
        team: TEAM_NAMES["The Zmeigorod Snessengers"],
        stats: {
          pass: 55,
          catch: 47,
          run: 42,
          block: 68,
          fight: 53,
          throw: 48,
          luck: 46,
          pronouns: "She/Her",
          civic_engagement: 50,
          alcohol_tolerance: 47,
          pregame_ritual:
            "Performing a series of aggressive, theatrical poses.",
          literate: true,
          favorite_weapon: "Spiked Gauntlet",
        },
      },
      {
        name: "Kleinstein MacGregor",
        team: TEAM_NAMES["The Zmeigorod Snessengers"],
        stats: {
          pass: 43,
          catch: 59,
          run: 61,
          block: 53,
          fight: 52,
          throw: 59,
          luck: 68,
          pronouns: "She/Her",
          civic_engagement: 52,
          alcohol_tolerance: 63,
          favorite_weapon: "Machete",
          pregame_ritual: "Clapping their hands a prime number of times.",
          literate: false,
        },
      },
      {
        name: "Avaria Revell",
        team: TEAM_NAMES["The Zmeigorod Snessengers"],
        stats: {
          pass: 53,
          catch: 46,
          run: 67,
          block: 50,
          fight: 54,
          throw: 57,
          luck: 61,
          pronouns: "She/Her",
          civic_engagement: 59,
          alcohol_tolerance: 66,
          favorite_weapon: "Bastard Sword",
          pregame_ritual:
            "Sharing a ceremonial, non-alcoholic grog from a communal cup.",
          literate: true,
        },
      },
      {
        name: "Alded Sanjay",
        team: TEAM_NAMES["The Zmeigorod Snessengers"],
        stats: {
          pass: 45,
          catch: 61,
          run: 56,
          block: 54,
          fight: 51,
          throw: 61,
          luck: 57,
          pronouns: "He/Him",
          civic_engagement: 58,
          alcohol_tolerance: 51,
          favorite_weapon: "War Scythe",
          pregame_ritual:
            "Looking each teammate in the eye and giving a single, firm nod.",
          literate: false,
        },
      },
      {
        name: "Arni Griffith",
        team: TEAM_NAMES["The Zmeigorod Snessengers"],
        stats: {
          pass: 47,
          catch: 62,
          run: 43,
          block: 56,
          fight: 51,
          throw: 55,
          luck: 53,
          pronouns: "He/Them",
          civic_engagement: 47,
          alcohol_tolerance: 49,
          favorite_weapon: "Woodsman's Axe",
          pregame_ritual:
            "Giving the Trollball a heroic backstory before each game.",
          literate: true,
        },
      },
      {
        name: "Dare Wynnie",
        team: TEAM_NAMES["The Zmeigorod Snessengers"],
        stats: {
          pass: 64,
          catch: 54,
          run: 50,
          block: 54,
          fight: 62,
          throw: 52,
          luck: 59,
          pronouns: "She/Them",
          civic_engagement: 60,
          alcohol_tolerance: 45,
          favorite_weapon: "Quarterstaff",
          pregame_ritual:
            "Painting a single, matching stripe of mud on each player's face.",
          literate: false,
        },
      },
    ],
  },
  [TEAM_NAMES["Oak & Onslaught"]]: {
    name: TEAM_NAMES["Oak & Onslaught"],
    slug: "oak-and-onslaught",
    losses: 0,
    wins: 0,
    score: 0,
    luck: 52,
    sponsor: "The Wardens",
    stadium: {
      name: "Fletchings Field",
      location: "Fletchings",
      description:
        "Fletchings Field was the first formal Troll Ball stadium in Warden lands. The design balances wood and stone, with arrowhead motifs and banners representing each region under Warden protection. The field includes trees, gully's and other obstacle placements, changed each match by local druids and terrain crafters.",
      modifiers: ["Shifting Terrain", "Warden's Watch", "Natural Advantages"],
    },
    healer: {
      name: "Ahron Latashia",
      team: TEAM_NAMES["Oak & Onslaught"],
      stats: {
        pass: 48,
        catch: 52,
        run: 56,
        block: 45,
        fight: 64,
        throw: 59,
        luck: 57,
        pronouns: "She/Her",
        civic_engagement: 68,
        alcohol_tolerance: 59,
        pregame_ritual:
          "Going over the game plan drawn in the dirt with the team captain.",
        literate: true,
        favorite_weapon: "Kriegsmesser",
      },
    },
    players: [
      {
        name: "Milt Casady",
        team: TEAM_NAMES["Oak & Onslaught"],
        stats: {
          pass: 54,
          catch: 57,
          run: 54,
          block: 65,
          fight: 47,
          throw: 65,
          luck: 52,
          pronouns: "He/Him",
          civic_engagement: 50,
          alcohol_tolerance: 44,
          favorite_weapon: "Blackjack",
          pregame_ritual:
            "Leading the team in a synchronized chant that slowly gets louder.",
          literate: false,
        },
      },
      {
        name: "Wynnie Faina",
        team: TEAM_NAMES["Oak & Onslaught"],
        stats: {
          pass: 50,
          catch: 64,
          run: 66,
          block: 55,
          fight: 51,
          throw: 60,
          luck: 71,
          pronouns: "He/Him",
          civic_engagement: 46,
          alcohol_tolerance: 72,
          favorite_weapon: "Mace",
          pregame_ritual:
            "Wearing their boots on the wrong feet during the warm-up.",
          literate: true,
        },
      },
      {
        name: "Normi Glaudia",
        team: TEAM_NAMES["Oak & Onslaught"],
        stats: {
          pass: 47,
          catch: 52,
          run: 64,
          block: 63,
          fight: 48,
          throw: 60,
          luck: 62,
          pronouns: "He/Him",
          civic_engagement: 47,
          alcohol_tolerance: 71,
          favorite_weapon: "Mallet",
          pregame_ritual:
            "Wearing their boots on the wrong feet during the warm-up.",
          literate: true,
        },
      },
      {
        name: "Symer Crissy",
        team: TEAM_NAMES["Oak & Onslaught"],
        stats: {
          pass: 53,
          catch: 53,
          run: 53,
          block: 55,
          fight: 44,
          throw: 63,
          luck: 58,
          pronouns: "She/Her",
          civic_engagement: 45,
          alcohol_tolerance: 63,
          favorite_weapon: "Pollaxe",
          pregame_ritual:
            "Giving the Trollball a heroic backstory before each game.",
          literate: true,
        },
      },
      {
        name: "Teria Ravo",
        team: TEAM_NAMES["Oak & Onslaught"],
        stats: {
          pass: 51,
          catch: 48,
          run: 54,
          block: 58,
          fight: 53,
          throw: 63,
          luck: 52,
          pronouns: "She/Them",
          civic_engagement: 47,
          alcohol_tolerance: 46,
          favorite_weapon: "War Pick",
          pregame_ritual: "Headbutting their own team's goal post (gently).",
          literate: true,
        },
      },
      {
        name: "Millham Evangeline",
        team: TEAM_NAMES["Oak & Onslaught"],
        stats: {
          pass: 53,
          catch: 48,
          run: 56,
          block: 44,
          fight: 56,
          throw: 62,
          luck: 57,
          pronouns: "They/Them",
          civic_engagement: 51,
          alcohol_tolerance: 49,
          favorite_weapon: "Bardiche",
          pregame_ritual:
            "Sticking a specific type of feather in their helmet's plume.",
          literate: true,
        },
      },
      {
        name: "Hole Bowerman",
        team: TEAM_NAMES["Oak & Onslaught"],
        stats: {
          pass: 39,
          catch: 49,
          run: 60,
          block: 64,
          fight: 60,
          throw: 49,
          luck: 58,
          pronouns: "She/Her",
          civic_engagement: 50,
          alcohol_tolerance: 51,
          favorite_weapon: "Lance",
          pregame_ritual:
            "Burying their helmet in the ground and then digging it back up.",
          literate: true,
        },
      },
      {
        name: "Affra Yanaton",
        team: TEAM_NAMES["Oak & Onslaught"],
        stats: {
          pass: 48,
          catch: 50,
          run: 63,
          block: 57,
          fight: 52,
          throw: 54,
          luck: 60,
          pronouns: "She/Them",
          civic_engagement: 57,
          alcohol_tolerance: 54,
          favorite_weapon: "Longsword",
          pregame_ritual:
            "Reading their own fortune in a scattering of knuckle bones.",
          literate: true,
        },
      },
      {
        name: "Abner Seidel",
        team: TEAM_NAMES["Oak & Onslaught"],
        stats: {
          pass: 55,
          catch: 61,
          run: 60,
          block: 56,
          fight: 54,
          throw: 51,
          luck: 58,
          pronouns: "He/Him",
          civic_engagement: 42,
          alcohol_tolerance: 54,
          favorite_weapon: "Talwar",
          pregame_ritual:
            "Wearing a specific, garishly colored pair of undergarments.",
          literate: true,
        },
      },
      {
        name: "Ema Ulrick",
        team: TEAM_NAMES["Oak & Onslaught"],
        stats: {
          pass: 53,
          catch: 54,
          run: 57,
          block: 57,
          fight: 52,
          throw: 66,
          luck: 52,
          pronouns: "She/Her",
          civic_engagement: 59,
          alcohol_tolerance: 56,
          favorite_weapon: "Cutlass",
          pregame_ritual:
            "Always putting on their left gauntlet before their right.",
          literate: false,
        },
      },
    ],
  },
  [TEAM_NAMES["The New Noxus Thorns"]]: {
    name: TEAM_NAMES["The New Noxus Thorns"],
    slug: "new-noxus-thorns",
    losses: 0,
    wins: 0,
    score: 0,
    luck: 36,
    sponsor: "The Blackthorn Company",
    stadium: {
      name: "The Cistern",
      location: "Noxus Subterrane",
      description:
        "An abandoned underground cistern repurposed as a subterranean arena. The damp stone field is perpetually slick with condensation, and pools of noxious runoff collect in the dark corners. The thick, stagnant air clings to the skin, and players must navigate the treacherous, wet perimeter with extreme caution to avoid the toxic hazards of the pit.",
      modifiers: [
        "Sewer Poison",
        "Slippery Condensation",
        "Abandoned Reservoir",
      ],
    },
    healer: {
      name: "Haeckel Millisent",
      team: TEAM_NAMES["The New Noxus Thorns"],
      stats: {
        pass: 50,
        catch: 48,
        run: 47,
        block: 59,
        fight: 54,
        throw: 60,
        luck: 58,
        pronouns: "They/Them",
        civic_engagement: 52,
        alcohol_tolerance: 54,
        current_alcohol: 0,
        favorite_weapon: "Arming Sword",
        pregame_ritual: "Trying to catch a fly with their bare hands.",
        literate: true,
      },
    },
    players: [
      {
        name: "Sashenka Jemimah",
        team: TEAM_NAMES["The New Noxus Thorns"],
        stats: {
          pass: 50,
          catch: 58,
          run: 58,
          block: 63,
          fight: 56,
          throw: 58,
          luck: 54,
          pronouns: "He/Him",
          civic_engagement: 59,
          alcohol_tolerance: 63,
          current_alcohol: 0,
          favorite_weapon: "Blackjack",
          pregame_ritual:
            "Getting a teammate to pour a bucket of cold water over their head.",
          literate: false,
        },
      },
      {
        name: "Ralf Johnna",
        team: TEAM_NAMES["The New Noxus Thorns"],
        stats: {
          pass: 51,
          catch: 54,
          run: 54,
          block: 50,
          fight: 56,
          throw: 49,
          luck: 43,
          pronouns: "They/Them",
          civic_engagement: 65,
          alcohol_tolerance: 43,
          current_alcohol: 0,
          favorite_weapon: "Stiletto",
          pregame_ritual:
            "Muttering a nonsensical rhyme to ward off bad spirits.",
          literate: true,
        },
      },
      {
        name: "Hanford Isaac",
        team: TEAM_NAMES["The New Noxus Thorns"],
        stats: {
          pass: 51,
          catch: 48,
          run: 48,
          block: 61,
          fight: 49,
          throw: 55,
          luck: 67,
          pronouns: "They/Them",
          civic_engagement: 47,
          alcohol_tolerance: 53,
          current_alcohol: 0,
          favorite_weapon: "Hand Axe",
          pregame_ritual:
            "Reciting their grocery list backward to clear their mind.",
          literate: true,
        },
      },
      {
        name: "Olodort Rossy",
        team: TEAM_NAMES["The New Noxus Thorns"],
        stats: {
          pass: 54,
          catch: 65,
          run: 60,
          block: 61,
          fight: 50,
          throw: 64,
          luck: 72,
          pronouns: "He/Him",
          civic_engagement: 62,
          alcohol_tolerance: 54,
          current_alcohol: 0,
          favorite_weapon: "Kirkhammer",
          pregame_ritual: "Chugging a small bottle of vinegar.",
          literate: false,
        },
      },
      {
        name: "Chae Markland",
        team: TEAM_NAMES["The New Noxus Thorns"],
        stats: {
          pass: 63,
          catch: 65,
          run: 59,
          block: 61,
          fight: 51,
          throw: 56,
          luck: 54,
          pronouns: "He/Him",
          civic_engagement: 57,
          alcohol_tolerance: 59,
          current_alcohol: 0,
          favorite_weapon: "Chain Whip",
          pregame_ritual: "Painting a crude, snarling face on their stomach.",
          literate: false,
        },
      },
      {
        name: "Slayton Nealon",
        team: TEAM_NAMES["The New Noxus Thorns"],
        stats: {
          pass: 52,
          catch: 48,
          run: 56,
          block: 47,
          fight: 49,
          throw: 55,
          luck: 44,
          pronouns: "He/Him",
          civic_engagement: 55,
          alcohol_tolerance: 64,
          current_alcohol: 0,
          favorite_weapon: "Mace",
          pregame_ritual: "Asking the referee to bless their weapon.",
          literate: true,
        },
      },
      {
        name: "Hulbig Addiel",
        team: TEAM_NAMES["The New Noxus Thorns"],
        stats: {
          pass: 54,
          catch: 53,
          run: 53,
          block: 49,
          fight: 60,
          throw: 59,
          luck: 59,
          pronouns: "She/Her",
          civic_engagement: 48,
          alcohol_tolerance: 54,
          current_alcohol: 0,
          favorite_weapon: "Woodsman's Axe",
          pregame_ritual: "Fasting for the six hours leading up to the match.",
          literate: true,
        },
      },
      {
        name: "Buffum Julie",
        team: TEAM_NAMES["The New Noxus Thorns"],
        stats: {
          pass: 49,
          catch: 69,
          run: 49,
          block: 48,
          fight: 62,
          throw: 51,
          luck: 60,
          pronouns: "She/Her",
          civic_engagement: 58,
          alcohol_tolerance: 62,
          current_alcohol: 0,
          favorite_weapon: "Kriegsmesser",
          pregame_ritual:
            "Organizing a small betting pool on who will score first.",
          literate: true,
        },
      },
      {
        name: "Nodababus Dee Dee",
        team: TEAM_NAMES["The New Noxus Thorns"],
        stats: {
          pass: 55,
          catch: 57,
          run: 54,
          block: 45,
          fight: 53,
          throw: 62,
          luck: 47,
          pronouns: "He/Him",
          civic_engagement: 60,
          alcohol_tolerance: 56,
          current_alcohol: 0,
          favorite_weapon: "Kirkhammer",
          pregame_ritual:
            "Huddling so tightly that no light can be seen between them.",
          literate: true,
        },
      },
      {
        name: "Husain Terrence",
        team: TEAM_NAMES["The New Noxus Thorns"],
        stats: {
          pass: 53,
          catch: 53,
          run: 54,
          block: 49,
          fight: 52,
          throw: 55,
          luck: 53,
          pronouns: "They/Them",
          civic_engagement: 58,
          alcohol_tolerance: 50,
          current_alcohol: 0,
          favorite_weapon: "Maul",
          pregame_ritual: "Braiding their hair into tight, battle-ready rows.",
          literate: true,
        },
      },
    ],
  },
  [TEAM_NAMES["The Dark Tree Demon Kids"]]: {
    name: TEAM_NAMES["The Dark Tree Demon Kids"],
    slug: "the-dark-tree-demon-kids",
    losses: 0,
    wins: 0,
    score: 0,
    luck: 51,
    sponsor: "Mellondor",
    stadium: {
      name: "Dark Tree Field",
      location: "Mellondor (Dark Tree)",
      description:
        "Located in the Cold North of Mundos Ferox, Mellondor’s settlement of Dark Tree lacks the funds for a proper stadium, but nature has provided a rugged open field just outside the settlement. The field is completely exposed to the elements, meaning players must contend with freezing rain, sheets of ice, and the tree's own grasping roots, while spectators warm themselves with blankets and campfires around the perimeter.",
      modifiers: ["Grasping Roots", "Freezing Rain", "Icy Field"],
    },
    healer: {
      name: "Bilski Sells",
      team: TEAM_NAMES["The Dark Tree Demon Kids"],
      stats: {
        pass: 56,
        catch: 52,
        run: 52,
        block: 57,
        fight: 53,
        throw: 52,
        luck: 56,
        pronouns: "He/Him",
        civic_engagement: 53,
        alcohol_tolerance: 52,
        current_alcohol: 0,
        favorite_weapon: "Scythe",
        pregame_ritual: "Attempting to communicate with birds.",
        literate: true,
      },
    },
    players: [
      {
        name: "Irma Patterman",
        team: TEAM_NAMES["The Dark Tree Demon Kids"],
        stats: {
          pass: 56,
          catch: 50,
          run: 55,
          block: 54,
          fight: 44,
          throw: 51,
          luck: 55,
          civic_engagement: 67,
          alcohol_tolerance: 49,
          current_alcohol: 0,
          favorite_weapon: "Dane Axe",
          pregame_ritual: "Eating a dandelion, stem and all.",
          literate: false,
        },
      },
      {
        name: "Cunningham Mapel",
        team: TEAM_NAMES["The Dark Tree Demon Kids"],
        stats: {
          pass: 57,
          catch: 45,
          run: 61,
          block: 48,
          fight: 63,
          throw: 59,
          luck: 56,
          pronouns: "He/Him",
          civic_engagement: 64,
          alcohol_tolerance: 73,
          current_alcohol: 0,
          favorite_weapon: "Claymore",
          pregame_ritual:
            "Mimicking the call of the regional 'Gloom-Lark' for courage.",
          literate: true,
        },
      },
      {
        name: "Far Studner",
        team: TEAM_NAMES["The Dark Tree Demon Kids"],
        stats: {
          pass: 55,
          catch: 55,
          run: 67,
          block: 59,
          fight: 51,
          throw: 54,
          luck: 58,
          pronouns: "They/Them",
          civic_engagement: 59,
          alcohol_tolerance: 69,
          current_alcohol: 0,
          favorite_weapon: "Boar Spear",
          pregame_ritual: "Painting a crude, snarling face on their stomach.",
          literate: true,
        },
      },
      {
        name: "Shinberg Weasner",
        team: TEAM_NAMES["The Dark Tree Demon Kids"],
        stats: {
          pass: 68,
          catch: 56,
          run: 47,
          block: 45,
          fight: 56,
          throw: 56,
          luck: 55,
          pronouns: "They/Them",
          civic_engagement: 49,
          alcohol_tolerance: 55,
          current_alcohol: 0,
          favorite_weapon: "Flail",
          pregame_ritual:
            "Tying a small, hand-carved wooden bird to their gear.",
          literate: true,
        },
      },
      {
        name: "Bor Jordanna",
        team: TEAM_NAMES["The Dark Tree Demon Kids"],
        stats: {
          pass: 58,
          catch: 55,
          run: 47,
          block: 48,
          fight: 49,
          throw: 54,
          luck: 55,
          civic_engagement: 43,
          alcohol_tolerance: 53,
          current_alcohol: 0,
          favorite_weapon: "Voulge",
          pregame_ritual:
            "Trying to teach a stray dog a complicated and useless new trick.",
          literate: true,
        },
      },
      {
        name: "Daniyal Velda",
        team: TEAM_NAMES["The Dark Tree Demon Kids"],
        stats: {
          pass: 62,
          catch: 61,
          run: 64,
          block: 39,
          fight: 45,
          throw: 37,
          luck: 57,
          pronouns: "She/Her",
          civic_engagement: 59,
          alcohol_tolerance: 60,
          current_alcohol: 0,
          favorite_weapon: "Sickle",
          pregame_ritual: "Attempting to communicate with birds.",
          literate: true,
        },
      },
      {
        name: "Gerianna Merwyn",
        team: TEAM_NAMES["The Dark Tree Demon Kids"],
        stats: {
          pass: 53,
          catch: 57,
          run: 51,
          block: 52,
          fight: 55,
          throw: 60,
          luck: 58,
          pronouns: "He/Him",
          civic_engagement: 58,
          alcohol_tolerance: 51,
          current_alcohol: 0,
          favorite_weapon: "Cudgel",
          pregame_ritual:
            "Eating a piece of honeycomb to 'sweeten' their victory.",
          literate: true,
        },
      },
      {
        name: "Jarid Tudela",
        team: TEAM_NAMES["The Dark Tree Demon Kids"],
        stats: {
          pass: 52,
          catch: 53,
          run: 45,
          block: 58,
          fight: 58,
          throw: 57,
          luck: 51,
          civic_engagement: 53,
          alcohol_tolerance: 59,
          current_alcohol: 0,
          favorite_weapon: "Billhook",
          pregame_ritual: "Chewing on tree bark.",
          literate: true,
        },
      },
      {
        name: "Ron Fairleigh",
        team: TEAM_NAMES["The Dark Tree Demon Kids"],
        stats: {
          pass: 50,
          catch: 50,
          run: 60,
          block: 59,
          fight: 56,
          throw: 48,
          luck: 55,
          pronouns: "He/Him",
          civic_engagement: 51,
          alcohol_tolerance: 42,
          current_alcohol: 0,
          favorite_weapon: "Swordstaff",
          pregame_ritual:
            "Chewing on a splinter of wood from a past goal basket.",
          literate: false,
        },
      },
      {
        name: "Stelmach Whitnell",
        team: TEAM_NAMES["The Dark Tree Demon Kids"],
        stats: {
          pass: 61,
          catch: 48,
          run: 62,
          block: 56,
          fight: 52,
          throw: 57,
          luck: 60,
          civic_engagement: 39,
          alcohol_tolerance: 62,
          current_alcohol: 0,
          favorite_weapon: "Maul",
          pregame_ritual:
            "Balancing the Trollball on their head for a full minute.",
          literate: true,
        },
      },
    ],
  },
} as Record<TEAM_NAMES, team>;
